---
- name: Install packages of neutron for controllers
  apt:
    name:
      - neutron-server
      - neutron-plugin-ml2
      - neutron-linuxbridge-agent
      - neutron-l3-agent
      - neutron-dhcp-agent
      - neutron-metadata-agent

- name: Set /etc/neutron/neutron.conf
  ansible.builtin.template:
    src: controllers/neutron/neutron.conf
    dest: /etc/neutron/neutron.conf
    owner: root
    group: neutron
    mode: '0640'
    backup: yes
  #notify:
  #  - Restart apache2

- name: Set /etc/neutron/plugins/ml2/ml2_conf.ini
  ansible.builtin.template:
    src: controllers/neutron/plugins/ml2/ml2_conf.ini
    dest: /etc/neutron/plugins/ml2/ml2_conf.ini
    owner: root
    group: neutron
    mode: '0640'
    backup: yes

