---
- name: Include init_glance_db/main.yml
  include: init_glance_db/main.yml

- name: Include create_glance_service/main.yml
  include: create_glance_service/main.yml

- name: Include create_endpoint/main.yml
  include: create_endpoint/main.yml

- name: Prepare glance
  include: prepare_glance/main.yml

- name: Create example cirros image
  include: create_example_cirros/main.yml

