---
#- name: Create a ssh_key on a master node of Ceph if it has not existed
#  openssh_keypair:
#    path: "{{ ansible_env.HOME }}/.ssh/ceph"
#  when: "inventory_hostname == group_vars.ceph.monitor.hosts.master"

#- name: Debug for cephs
#  ansible.builtin.debug:
#    msg: "{{ item }}"
#  with_items:
#    "group_vars.hosts['cephs']"
#  when: "'cephs' in group_vars.hosts"

- name: Installing packages for Ceph nodes
  apt:
    name:
      - ceph
  register: apt_result
  retries: 360
  delay: 5
  until: apt_result is success

- name: Register a variable file_ceph_cluster_uuid_stat to check a file .uuid_for_ceph_cluster has alreadu existed
  stat:
    path: "{{ ansible_env.HOME }}/.uuid_for_ceph_cluster"
    get_checksum: false
    get_md5: false
  register: file_ceph_uuid_stat

- name: Create uuid for ceph cluster
  copy:
    dest: "{{ ansible_env.HOME }}/.uuid_for_ceph_cluster"
    content: "{{ 9999999999999999999999 | random | to_uuid }}"
  when: file_ceph_uuid_stat.stat.exists == False and inventory_hostname == group_vars.ceph.monitor.hosts.master

- name: "Fetch the file \"{{ ansible_env.HOME }}/.uuid_for_ceph_cluster\" from the  to push any swift nodes"
  run_once: yes
  fetch:
    src: "{{ ansible_env.HOME }}/.uuid_for_ceph_cluster"
    dest: .buffer/.uuid_for_ceph_cluster
    flat: yes
  when: inventory_hostname == group_vars.ceph.monitor.hosts.master

- name: "Declare a variable to push UUID for Ceph cluster"
  set_fact:
    uuid_for_ceph_cluster: "{{ lookup('file', \".buffer/.uuid_for_ceph_cluster\") }}"

- name: "Checking whether getting UUID for Ceph cluster has succeeded"
  ansible.builtin.fail:
    msg: "Failed getting UUID from a file \"{{ ansible_env.HOME }}/.uuid_for_ceph_cluster\" from the host \"{{ group_vars.ceph.monitor.hosts.master }}\". Result of value of the variable is \"{{ uuid_for_ceph_cluster }}\""
  when: not uuid_for_ceph_cluster | regex_search("^[0-9a-f]{8}\-[0-9a-f]{4}\-[0-9a-f]{4}\-[0-9a-f]{4}\-[0-9a-f]{12}$")

- name: "Print for a variable uuid_for_ceph_cluster"
  ansible.builtin.debug:
    msg: "uuid_for_ceph_cluster={{ uuid_for_ceph_cluster }}"

- name: "Declare a list of host to modify \"/etc/ceph/ceph.conf\" if current host \"{{ inventory_hostname }}\" is in \"group_vars.hosts.cinders\""
  set_fact:
    my_ip: "{% if 'cinders' in group_vars.hosts %}{% set tmp_hosts = group_vars.hosts.cinders %}{% elif 'storages' in group_vars.hosts %}{% set tmp_hosts = group_vars.hosts.storages %}{% endif -%}
            {% if tmp_hosts is defined -%}
              {% for item in tmp_hosts -%}
                {% if item.name == group_vars.ceph.monitor.hosts.master -%}{{ item.management.ip }}{% endif -%}
              {% endfor -%}
            {% endif %}"
  when: inventory_hostname == group_vars.ceph.monitor.hosts.master

- name: "Print a variable \"my_ip\" if a current host \"{{ inventory_hostname }}\" is a monitor of Ceph cluster"
  ansible.builtin.debug:
    msg: "my_ip={{ my_ip }}"
  when: inventory_hostname == group_vars.ceph.monitor.hosts.master

- name: "Failed if a variable \"my_ip\" has not defined in a monitor node of Ceph \"{{ inventory_hostname }}\""
  ansible.builtin.fail:
    msg: "Failed! A variable \"my_ip\" has not defined in a monitor node of Ceph \"{{ inventory_hostname }}\". Does a host \"{{ inventory_hostname }}\" existed in \"group_vars.hosts.cinders\" or \"group_vars.hosts.storages\"?"
  when: (inventory_hostname == group_vars.ceph.monitor.hosts.master) and (not my_ip | regex_search("^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$"))

- name: "Creating /etc/ceph/ceph.conf only in a host \"{{ group_vars.ceph.monitor.hosts.master }}\""
  ansible.builtin.template:
    src: monitor/etc/ceph/ceph.conf
    dest: /etc/ceph/ceph.conf
    owner: root
    group: root
    mode: '0644'
  #notify:
  #  - Restart rsync
  when: inventory_hostname == group_vars.ceph.monitor.hosts.master

- name: "Generating a key for monitoring a Ceph cluster on \"{{ group_vars.ceph.monitor.hosts.master }}\""
  ansible.builtin.command: ceph-authtool --create-keyring /etc/ceph/ceph.mon.keyring --gen-key -n mon. --cap mon 'allow *'
  when: inventory_hostname == group_vars.ceph.monitor.hosts.master

- name: "Generating a key for managing a Ceph cluster on \"{{ group_vars.ceph.monitor.hosts.master }}\""
  ansible.builtin.command: ceph-authtool --create-keyring /etc/ceph/ceph.client.admin.keyring --gen-key -n client.admin --cap mon 'allow *' --cap osd 'allow *' --cap mds 'allow *' --cap mgr 'allow *'
  when: inventory_hostname == group_vars.ceph.monitor.hosts.master

- name: "Generating a key for bootstraping a Ceph cluster on \"{{ group_vars.ceph.monitor.hosts.master }}\""
  ansible.builtin.command: ceph-authtool --create-keyring /var/lib/ceph/bootstrap-osd/ceph.keyring --gen-key -n client.bootstrap-osd --cap mon 'profile bootstrap-osd' --cap mgr 'allow r'
  when: inventory_hostname == group_vars.ceph.monitor.hosts.master

- name: "Import a keyring \"client.admin\" from \"/etc/ceph/ceph.client.admin.keyring\" to \"/etc/ceph/ceph.mon.keyring\""
  ansible.builtin.command: ceph-authtool /etc/ceph/ceph.mon.keyring --import-keyring /etc/ceph/ceph.client.admin.keyring
  when: inventory_hostname == group_vars.ceph.monitor.hosts.master

- name: "Import a key \"client.bootstrap-osd\" from \"/var/lib/ceph/bootstrap-osd/ceph.keyring\" to \"/etc/ceph/ceph.mon.keyring\"."
  ansible.builtin.command: ceph-authtool /etc/ceph/ceph.mon.keyring --import-keyring /var/lib/ceph/bootstrap-osd/ceph.keyring
  when: inventory_hostname == group_vars.ceph.monitor.hosts.master

- name: "Creating a monitor-map for Ceph cluster on a monitor node \"{{ group_vars.ceph.monitor.hosts.master }}\""
  ansible.builtin.command: monmaptool --create --add {{ inventory_hostname }} {{ my_ip }} --fsid {{ uuid_for_ceph_cluster }} /etc/ceph/monmap
  when: inventory_hostname == group_vars.ceph.monitor.hosts.master

- name: "Creating a directory \"/var/lib/ceph/mon/ceph-{{ group_vars.ceph.monitor.hosts.master }}\" for a daemon of Ceph monitor"
  ansible.builtin.file:
    path: "/var/lib/ceph/mon/ceph-{{ group_vars.ceph.monitor.hosts.master }}"
    state: directory
    mode: '0755'
  when: inventory_hostname == group_vars.ceph.monitor.hosts.master

- name: "Creating a monitor-map for Ceph cluster on a monitor node \"{{ group_vars.ceph.monitor.hosts.master }}\""
  ansible.builtin.command: monmaptool --create --add {{ inventory_hostname }} {{ my_ip }} --fsid {{ uuid_for_ceph_cluster }} /etc/ceph/monmap
  when: inventory_hostname == group_vars.ceph.monitor.hosts.master

- name: "Create a monitor daemon of Ceph"
  ansible.builtin.command: ceph-mon --cluster ceph --mkfs -i {{ group_vars.ceph.monitor.hosts.master }} --monmap /etc/ceph/monmap --keyring /etc/ceph/ceph.mon.keyring
  when: inventory_hostname == group_vars.ceph.monitor.hosts.master

