---
#- name: Create a ssh_key on a master node of Ceph if it has not existed
#  openssh_keypair:
#    path: "{{ ansible_env.HOME }}/.ssh/ceph"
#  when: "inventory_hostname == group_vars.ceph.monitor.hosts.master"

#- name: Debug for cephs
#  ansible.builtin.debug:
#    msg: "{{ item }}"
#  with_items:
#    "group_vars.hosts['cephs']"
#  when: "'cephs' in group_vars.hosts"

- name: "Declare primary_group_name as \"cinders\""
  set_fact:
    primary_group_name: "cinders"
  when: '"cinders" in group_names'

- name: "Declare primary_group_name as \"storages\""
  set_fact:
    primary_group_name: "storages"
  when: '"storages" in group_names'

- name: "Declare primary_group_name as \"computes\""
  set_fact:
    primary_group_name: "computes"
  when: '"computes" in group_names'

- name: "Check whether a variable \"primary_group_name\" has declared"
  ansible.builtin.fail:
    msg: "Failed due to undefined variable \"primary_group_name\". Current node \"{{ inventory_hostname }}\" must belonging in \"cinders\" or \"storages\" or \"computes\"."
  when: primary_group_name is not defined


- name: "Include \"install_packages/monitors/main.yml\" if a current host is a monitor of Ceph. // Conditionals -> \"inventory_hostname({{ inventory_hostname }}) == group_vars.ceph.monitor.hosts.master({{ group_vars.ceph.monitor.hosts.master }})\""
  include_tasks: install_packages/monitors/main.yml
  when: (primary_group_name == "cinders" or primary_group_name == "storages") and (inventory_hostname == group_vars.ceph.monitor.hosts.master)

- name: "Include \"install_packages/nodes/main.yml\" if a current host is a monitor of Ceph. // conditionals -> \"inventory_hostname({{ inventory_hostname }}) != group_vars.ceph.monitor.hosts.master({{ group_vars.ceph.monitor.hosts.master }})\""
  include_tasks: install_packages/nodes/main.yml
  when: (primary_group_name == "cinders" or primary_group_name == "storages") and (inventory_hostname != group_vars.ceph.monitor.hosts.master)


- name: Block for monitor node for Ceph cluster
  block:

  - name: "Include create_ceph_conf/monitors/main.yml for monitor node of Ceph"
    include_tasks: create_ceph_conf/monitors/main.yml

  - name: "Include create_keyrings/monitors/main.yml for monitor node of Ceph"
    include_tasks: create_keyrings/monitors/main.yml

  - name: "Include create_monitors/monitors/main.yml for monitor node of Ceph"
    include_tasks: create_monitors/monitors/main.yml

  - name: "Include configure_ceph/monitors/main.yml for monitor node of Ceph"
    include_tasks: configure_ceph/monitors/main.yml

  - name: "Include create_managers/managers/main.yml for manager node of Ceph"
    include_tasks: create_managers/managers/main.yml

  - name: "Include print_current_stat/managers/main.yml"
    include_tasks: print_current_stat/managers/main.yml

  - name: "Include fetch_resources_to_copy_to_other_nodes/managers/main.yml"
    include_tasks: fetch_resources_to_copy_to_other_nodes/managers/main.yml

  when: (primary_group_name == "cinders" or primary_group_name == "storages") and (inventory_hostname == group_vars.ceph.monitor.hosts.master)

- name: Block for general nodes for Ceph cluster
  block:

  - name: "Include push_resources_to_other_nodes/monitors/main.yml for monitor node of Ceph"
    include_tasks: push_resources_to_other_nodes/monitors/main.yml

  when: (primary_group_name == "cinders" or primary_group_name == "storages") and (inventory_hostname != group_vars.ceph.monitor.hosts.master)

- name: "Include create_ceph_volume/common/main.yml"
  include_tasks: create_ceph_volume/common/main.yml
  when: primary_group_name == "cinders" or primary_group_name == "storages"

- name: "Include print_current_stat/managers/main.yml"
  include_tasks: print_current_stat/managers/main.yml
  when: inventory_hostname == group_vars.ceph.monitor.hosts.master

