---
- name: Create a ssh_key on a master node of Ceph if it has not existed
  openssh_keypair:
    path: "{{ ansible_env.HOME }}/.ssh/ceph"
  when: "inventory_hostname == group_vars.ceph.monitor.hosts.master"

#- name: Debug for cephs
#  ansible.builtin.debug:
#    msg: "{{ item }}"
#  with_items:
#    "group_vars.hosts['cephs']"
#  when: "'cephs' in group_vars.hosts"

