---
#- name: Create a ssh_key on a master node of Ceph if it has not existed
#  openssh_keypair:
#    path: "{{ ansible_env.HOME }}/.ssh/ceph"
#  when: "inventory_hostname == group_vars.ceph.monitor.hosts.master"

#- name: Debug for cephs
#  ansible.builtin.debug:
#    msg: "{{ item }}"
#  with_items:
#    "group_vars.hosts['cephs']"
#  when: "'cephs' in group_vars.hosts"

- name: "Include \"install_packages/monitors/main.yml\" if a current host is a monitor of Ceph. // Conditionals -> \"inventory_hostname({{ inventory_hostname }}) == group_vars.ceph.monitor.hosts.master({{ group_vars.ceph.monitor.hosts.master }})\""
  include_tasks: install_packages/monitors/main.yml
  when: inventory_hostname == group_vars.ceph.monitor.hosts.master

- name: "Include \"install_packages/nodes/main.yml\" if a current host is a monitor of Ceph. // conditionals -> \"inventory_hostname({{ inventory_hostname }}) != group_vars.ceph.monitor.hosts.master({{ group_vars.ceph.monitor.hosts.master }})\""
  include_tasks: install_packages/nodes/main.yml
  when: inventory_hostname != group_vars.ceph.monitor.hosts.master


- name: Block for monitor node for Ceph cluster
  block:

  - name: "Include create_ceph_conf/monitors/main.yml for monitor node of Ceph"
    include_tasks: create_ceph_conf/monitors/main.yml

  - name: "Include create_keyrings/monitors/main.yml for monitor node of Ceph"
    include_tasks: create_keyrings/monitors/main.yml

  - name: "Include create_monitors/monitors/main.yml for monitor node of Ceph"
    include_tasks: create_monitors/monitors/main.yml

  - name: "Include configure_ceph/monitors/main.yml for monitor node of Ceph"
    include_tasks: configure_ceph/monitors/main.yml

  - name: "Include create_managers/managers/main.yml for manager node of Ceph"
    include_tasks: create_managers/managers/main.yml


  - name: "Run a command \"ceph osd lspools\" to list Ceph pools"
    ansible.builtin.command: ceph osd lspools
    register: result_of_command

  - name: "Print a result of \"ceph osd lspools\""
    ansible.builtin.debug:
      msg: "{{ result_of_command.stdout.split('\n') }}"

  - name: "Run a command \"ceph -s\" to show Ceph status"
    ansible.builtin.command: ceph -s
    register: result_of_command

  - name: "Print a result of \"ceph -s\""
    ansible.builtin.debug:
      msg: "{{ result_of_command.stdout.split('\n') }}"

  - name: "Run a command \"ceph osd tree\" to show OSD tree"
    ansible.builtin.command: ceph osd tree
    register: result_of_command

  - name: "Print a result of \"ceph osd tree\""
    ansible.builtin.debug:
      msg: "{{ result_of_command.stdout.split('\n') }}"

  - name: "Run a command \"ceph df\" to show Ceph device space usage"
    ansible.builtin.command: ceph df
    register: result_of_command

  - name: "Print a result of \"ceph df\""
    ansible.builtin.debug:
      msg: "{{ result_of_command.stdout.split('\n') }}"

  - name: "Run a command \"ceph osd df\" to show OSD device space usage"
    ansible.builtin.command: ceph osd df
    register: result_of_command

  - name: "Print a result of \"ceph osd df\""
    ansible.builtin.debug:
      msg: "{{ result_of_command.stdout.split('\n') }}"

  when: inventory_hostname == group_vars.ceph.monitor.hosts.master

