---
# Create example network

- name: Include do_create_network.yml
  include_tasks: do_create_network.yml
  loop_control:
    loop_var: tmp_network
  loop: "{{ group_vars.openstack.examples.networks }}"

- name: List openstack network after creating networks
  ansible.builtin.command:
    argv: ["openstack", "network", "list"]
  register: result

- name: Print the result of "openstack network list" after creating networks
  ansible.builtin.debug:
    msg: "{{ result.stdout.split('\n') }}"

