---
- name: A block to build Cinder for controller nodes
  block:
    - name: Include create_dbs/main.yml
      include_tasks: create_dbs/main.yml

    - name: Include create_services/main.yml
      include_tasks: create_services/main.yml

    - name: Include create_endpoints/main.yml
      include_tasks: create_endpoints/main.yml

    - name: Include install_packages/controllers/main.yml of cinder for controllers
      include_tasks: install_packages/controllers/main.yml

    - name: Include set_configuration/controllers/main.yml of cinder for controllers
      include_tasks: set_configuration/controllers/main.yml

    - name: Include cinder_manage_db_sync/main.yml for controllers
      include_tasks: cinder_manage_db_sync/main.yml

    # Get swift_url and transfer it to cinder node in order to configure cinder.conf on Cinder nodes.
    - name: Include get_backup_swift_url/main.yml
      include_tasks: get_backup_swift_url/main.yml
  when: "'controllers' in group_names"

- name: A block to build Cinder for cinder nodes
  block:
    - name: Include set_lvm/main.yml of cinder for controllers
      include_tasks: set_lvm/main.yml

    - name: Include install_packages/cinders/main.yml
      include_tasks: install_packages/cinders/main.yml

    - name: Include set_configuration/cinders/main.yml of cinder for controllers
      include_tasks: set_configuration/cinders/main.yml
  when: "'cinders' in group_names"

- name: A block to build Cinder for compute nodes
  block:
    - name: Include set_services_of_cinder_for_computes/main.yml
      include_tasks: set_services_of_cinder_for_computes/main.yml
  when: "'computes' in group_names"
