---
##- name: Get an config-element of this node.
##  set_fact:
##    config_element_of_swift: "{{ tmp_config_element_of_swift }}"
##  when: tmp_config_element_of_swift.name == inventory_hostname
##  loop_control:
##    loop_var:
##      tmp_config_element_of_swift
##  with_items: "{{ group_vars.hosts.swifts }}"

- name: "Failed if there is no element of the config for Swift node \"{{ inventory_hostname }}\"."
  ansible.builtin.fail:
    msg: "Failed if there is no element of the config for Swift node \"{{ inventory_hostname }}\"."
  when: config_element_of_swift | length <= 0

- name: "Debug config_element_of_swift for the node \"{{ inventory_hostname }}\"."
  ansible.builtin.debug:
    msg: "config_element_of_swift -> {{ config_element_of_swift }}"

- name: "Include mount_storage_for_swift_node/main.yml"
  include_tasks: mount_storage_for_swift_node/main.yml
  loop_control:
    loop_var:
      name_of_device_for_swift
  with_items: "{{ config_element_of_swift.storage.swift }}"

- name: "Mount all after /etc/fstab has been modified."
  ansible.builtin.command:
    argv: ["mount", "-a"]
