---
- hosts: cinders
  become: yes
  roles:
    - { role: ntp, tags: ['role_ntp']}
    - { role: add_openstack_repository, tags: ['role_add_openstack_repository']}
    #- { role: cinder, tags: ['role_cinder']}
    #- { role: neutron, tags: ['role_neutron']}
