---
- hosts: computes
  become: yes
  roles:
    - { role: ntp, tags: ['role_ntp']}
    - { role: add_openstack_repository, tags: ['role_add_openstack_repository']}
    - { role: nova, tags: ['role_nova']}
    - { role: neutron, tags: ['role_neutron']}
