---
- hosts: controllers
  become: yes
  roles:
    - { role: ntp, tags: ['role_ntp']}
    - { role: sql, tags: ['role_sql']}
    - { role: mq, tags: ['role_mq']}
    - { role: memcached, tags: ['role_memcached']}
    - { role: etcd, tags: ['role_etcd']}
    - { role: add_openstack_repository, tags: ['role_add_openstack_repository']}
    - { role: keystone, tags: ['role_keystone']}
    - { role: glance, tags: ['role_glance']}
    - { role: placement, tags: ['role_placement']}
    - { role: nova, tags: ['role_nova']}
    #- { role: neutron, tags: ['role_neutron']}
    #- { role: horizon, tags: ['role_horizon']}
  environment:
    OS_USERNAME: admin
    OS_PASSWORD: "{{ group_vars.openstack.admin_password }}"
    OS_PROJECT_NAME: admin
    OS_USER_DOMAIN_NAME: Default
    OS_PROJECT_DOMAIN_NAME: Default
    OS_AUTH_URL: "{{ group_vars.keystone.auth_url }}"
    OS_IDENTITY_API_VERSION: 3
