---
- hosts: controllers
  become: yes
  roles:
    - { role: test_env, tags: ['role_test_env']}
  environment:
    OS_USERNAME: admin
    OS_PASSWORD: "{{ group_vars.openstack.admin_password }}"
    OS_PROJECT_NAME: admin
    OS_USER_DOMAIN_NAME: Default
    OS_PROJECT_DOMAIN_NAME: Default
    OS_AUTH_URL: "{{ group_vars.keystone.auth_url }}"
    OS_IDENTITY_API_VERSION: 3
    # Environment variables below will be used only in a role "test_env"
    PROJECT_LIST_CACHE_FILE: "ansible_openstack_project_list"
