---
- hosts: controllers
  become: yes
  roles:
    - { role: ntp, tags: ['always']}
    - { role: sql, tags: ['always']}
    - { role: mq, tags: ['always']}
    - { role: memcached, tags: ['always']}
    - { role: etcd, tags: ['always']}
    - { role: add_openstack_repository, tags: ['always']}
    - { role: keystone, tags: ['always']}
    - { role: glance, tags: ['always']}
    - { role: placement, tags: ['always']}
    - { role: nova, tags: ['always']}
    - { role: neutron, tags: ['always']}
    - { role: horizon, tags: ['always']}
    - { role: test_env, tags: ['always']}
  environment:
    OS_USERNAME: admin
    OS_PASSWORD: "{{ group_vars.openstack.admin_password }}"
    OS_PROJECT_NAME: admin
    OS_USER_DOMAIN_NAME: Default
    OS_PROJECT_DOMAIN_NAME: Default
    OS_AUTH_URL: "{{ group_vars.keystone.auth_url }}"
    OS_IDENTITY_API_VERSION: 3
