---
# Variables
#   element_of_node.storage.cinder

- name: "Do debug print for creating ceph volumes"
  ansible.builtin.debug:
    msg: "{{ element_of_node }}"

- name: "Run create_ceph_volume.sh with args [\"{{ item }}\"]"
  script: ./create_ceph_volume.sh "{{ item }}"
  with_items: "{{ element_of_node.storage.cinder }}"
