---
- name: "Include a function declare_variable_primary_group_name/main.yml"
  include_role:
    name: functions
    tasks_from: declare_variable_primary_group_name/main.yml

- name: "Debug a variable \"primary_group_name\""
  ansible.builtin.debug:
    msg: "primary_group_name = {{ primary_group_name }}"

- name: Include format_volumes/main.yml
  include: format_volumes/main.yml
  when: primary_group_name == "cinders" or primary_group_name == "swift" or primary_group_name == "storages" or primary_group_name == "comstorages"
