---
- name: Install packages of Nova controller node
  apt:
    name:
      - nova-api
      - nova-conductor
      - nova-novncproxy
      - nova-scheduler
  register: apt_result
  retries: 360
  delay: 5
  until: apt_result is success
