---
# swift_node
#   A node of Swift that has a key'storage'.
# swift_node.storage.swift
#   Storages of Swift

- name: "Check whether the key \"swift_node.storage\" is existed"
  ansible.builtin.fail:
    msg: "A parameter \"swift_node\" must have a key \"storage\"."
  when: not 'storage' in swift_node

- name: "Check whether the key \"swift_node.storage.swift\" is existed"
  ansible.builtin.fail:
    msg: "A parameter \"swift_node\" must have a key \"storage.swift\"."
  when: not 'swift' in swift_node.storage

- name: Include a function adding {{ type_of_builder }} of device for Swift
  include_role:
    name: functions
    tasks_from: add_swift_ring/main.yml
  vars:
    builder: "{{ type_of_builder }}"
    ip_of_storage_node: "{{ swift_node.management.ip }}"
  loop_control:
    loop_var: name_of_device
  with_items: "{{ swift_node.storage.swift }}"
