---
- name: Stat /etc/swift/account.builder to detect a ring of account.builder has already created
  stat:
    path: /etc/swift/account.builder
  register: stat_account_builder

- name: Include create_swift_ring/main.yml in a role function
  include_role:
    name: functions
    tasks_from: create_swift_ring/main.yml
  vars:
    type_of_builder: "account.builder"
  when: not stat_account_builder.stat.exists
