---
# Variables will passed in this instruction.
# * swift_object_server
#   A Swift object builder.
#
# * swift_object_server.name
#   A name of object server.
#
# * swift_object_server.port
#   A port number of the server

- name: "Declare a variable \"builder\""
  set_fact:
    object_server_name: "{{ swift_object_server.name }}"
    builder: "{{ swift_object_server.name }}.builder"
    builder_port: "{{ swift_object_server.port }}"

- name: "Stat /etc/swift/{{ builder }} to detect a ring of account.builder has already created"
  stat:
    path: "/etc/swift/{{ builder }}"
  register: stat_builder

- name: Include do_create_ring.yml
  include: do_create_ring.yml
  when: not stat_builder.stat.exists

- name: Include add_swift_ring_builder_for_each_nodes.yml
  include: add_swift_ring_builder_for_each_nodes.yml
  loop_control:
    loop_var: swift_node
  with_items: "{{ group_vars.hosts.swifts }}"

- name: "Rebalance Swift ring builder for the builder \"{{ builder }}\""
  ansible.builtin.command:
    cmd: swift-ring-builder {{ object_server_name }} rebalance
  args:
    chdir: /etc/swift

# TODO: Wait antil

