---
# Variables will passed in this instruction.
# * swift_object_server
#   A Swift object builder.
#
# * swift_object_server.name
#   A name of object server.
#
# * swift_object_server.port
#   A port number of the server
#
# * target_storage_nodes

- name: "Declare a variable \"builder\""
  set_fact:
    builder: "{{ swift_object_server.name }}.builder"
    builder_port: "{{ swift_object_server.port }}"

- name: "Stat /etc/swift/{{ builder }} to detect a ring of account.builder has already created"
  stat:
    path: "/etc/swift/{{ builder }}"
  register: stat_builder

- name: Include do_create_ring.yml
  include_tasks: do_create_ring.yml
  when: not stat_builder.stat.exists

- name: Declare a variable target_swift_nodes
  set_fact:
    target_swift_nodes: []

- name: Join group_vars.hosts.swifts to a variable target_swift_nodes
  set_fact:
    target_swift_nodes: "{{ target_swift_nodes + group_vars.hosts.swifts }}"
  when: '{{ "swifts" in group_vars.hosts }}'

- name: Join group_vars.hosts.storages to a variable target_swift_nodes
  set_fact:
    target_swift_nodes: "{{ target_swift_nodes + group_vars.hosts.storages }}"
  when: '{{ "storages" in group_vars.hosts }}'

- name: Include add_swift_ring_builder_for_each_nodes.yml
  include_tasks: add_swift_ring_builder_for_each_nodes.yml
  loop_control:
    loop_var: swift_node
  with_items: "{{ target_storage_nodes }}"

- name: "Rebalance Swift ring builder for the builder \"{{ builder }}\""
  ansible.builtin.command:
    cmd: swift-ring-builder {{ builder }} rebalance
  args:
    chdir: /etc/swift

# TODO: Wait antil

