---
# * type_of_builder:
#   A type of builder like "account.builder", "container.builder", "object.builder".

- name: Stat /etc/swift/account.builder to detect a ring of account.builder has already created
  stat:
    path: /etc/swift/account.builder
  register: stat_account_builder

- name: Include create_swift_ring/main.yml in a role function
  include_role:
    name: functions
    tasks_from: create_swift_ring/main.yml
  vars:
    type_of_builder: "{{ type_of_builder }}"
  when: not stat_account_builder.stat.exists

- name: Include add_swift_ring_builder_for_each_nodes.yml
  include: add_swift_ring_builder_for_each_nodes.yml
  loop_control:
    loop_var: swift_node
  vars:
    type_of_builder: "{{ type_of_builder }}"
  with_items: "{{ group_vars.hosts.swifts }}"
