---
# Variables will passed in this instruction.
# * builder (type String)
#   A type of builder for Swift.
#   Accepted values are "account.builder", "container.builder", "object.builder".

- name: "Create builder for Swift. A type of builder is \"{{ builder }}\""
  ansible.builtin.command:
    cmd: swift-ring-builder {{ builder }} create 10 3 1
  args:
    chdir: /etc/swift

- name: "Wait until the file /etc/swift/{{ builder }} has been created."
  ansible.builtin.wait_for:
    path: "/etc/swift/{{ builder }}"
