---
- name: Declare empty hash to create rings for Swift
  set_fact:
    map_of_swift_nodes: []

- name: Merge hash of swifts to create rings for Swift
  set_fact:
    #map_of_swift_nodes: "{{ map_of_swift_nodes | hash_merge(group_vars.hosts) }}"
    map_of_swift_nodes: "{{ map_of_swift_nodes + group_vars.hosts.swifts }}"
  when: "'controllers' in groups and 'swifts' in group_vars.hosts"

#- name: Merge hash of swifts to create rings for Swift
#  set_fact:
#    map_of_swift_nodes: "{{ map_of_swift_nodes | hash_merge(storages) }}"
#  when: "'storages' in groups"

###- name: Combine 01
###  set_fact:
###    options: []
###
###- name: Combine 02
###  set_fact:
###    options: "{{ options + [\"--swift-device\", item] }}"
###  with_items: "{{ group_vars.hosts.swifts[0].storage.swift }}"
###
###- name: Combine 02
###  set_fact:
###    options: "{{ options + [\"--cinder-device\", item] }}"
###  with_items: "{{ group_vars.hosts.swifts[0].storage.cinder }}"
###
###
###- name: Deeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeebug
###  ansible.builtin.debug:
###    msg: "map_of_swift_nodes={{ map_of_swift_nodes }}, option={{ options }}"

- name: Include create_account_ring.yml
  include_tasks: create_account_ring.yml
  with_dict: 
