---
- name: Declare empty hash to create rings for Swift
  set_fact:
    map_of_swift_nodes: []

- name: Merge hash of swifts to create rings for Swift
  set_fact:
    #map_of_swift_nodes: "{{ map_of_swift_nodes | hash_merge(group_vars.hosts) }}"
    map_of_swift_nodes: "{{ map_of_swift_nodes + group_vars.hosts.swifts }}"
  when: "'controllers' in groups and 'swifts' in group_vars.hosts"

#- name: Merge hash of swifts to create rings for Swift
#  set_fact:
#    map_of_swift_nodes: "{{ map_of_swift_nodes | hash_merge(storages) }}"
#  when: "'storages' in groups"


- name: Deeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeebug
  ansible.builtin.debug:
    msg: "map_of_swift_nodes={{ map_of_swift_nodes }}"

#- name: Include create_account_ring.yml
#  include_tasks: create_account_ring.yml
#  with_dict: 
