---
- name: Declare empty hash to create rings for Swift
  set_fact:
    map_of_swift_nodes: []

- name: Include create_account_ring.yml
  include_tasks: create_account_ring.yml
  loop_control:
    loop_var: type_of_builder
  with_items:
    - "account.builder"
    - "container.builder"
    - "object.builder"
