---
- name: Include create_rings.yml
  include_tasks: create_rings.yml
  loop_control:
    loop_var: type_of_builder
  with_items:
    - "account.builder"
    - "container.builder"
    - "object.builder"
