---
- name: Install packages for rabbitmq-server
  apt:
    name:
      - rabbitmq-server

- name: Check openstack user has already existed in rabbitmq
  ansible.builtin.script:
    cmd: check_existence_of_user.sh {{ group_vars.mq.user }}
  register: ret
  failed_when: ret.rc not in [0, 1]

- name: Add user openstack for rabbitmq
  ansible.builtin.command:
   argv:
    - rabbitmqctl
    - add_user
    - "{{ group_vars.mq.user }}"
    - "{{ group_vars.mq.password }}"
  when: ret.rc != 0

- name: Set permission of rabbitmq
  ansible.builtin.command:
    argv:
      - rabbitmqctl
      - set_permissions
      - "{{ group_vars.mq.user }}"
      - ".*"
      - ".*"
      - ".*"
  when: ret.rc != 0

- name: Rabbitmq should be enabled
  ansible.builtin.systemd:
    name: rabbitmq-server
    enabled: yes

