---
- name: Install packages of Neutron for controllers with OVN
  apt:
    name:
      - neutron-server
      - neutron-plugin-ml2
      - python3-neutronclient
      - ovn-central
      - openvswitch-switch
