---
- name: Install packages of Neutron for controllers with OVN
  apt:
    name:
      - neutron-server
      - neutron-plugin-ml2
      - python3-neutronclient
      - ovn-central
      - openvswitch-switch
    update_cache: yes
  register: apt_result
  retries: 360
  delay: 5
  until: apt_result is success
