---
# Parameters:
#
# * service_name (type String)
#   A service name of OpenStack service. eg) "glance", "placement" etc.
#
# * service_type (type String)
#   Type of OpenStack service. eg) "image(glance)", "placement" etc.
#
# * service_description (type String)
#   Description of the OpenStack service.
#

- name: Check the service is already existed or not
  ansible.builtin.script: ./check_duplicate_openstack_service.sh "{{ service_name }}" "{{ service_type }}"
  register: result_of_checking
  failed_when: ( result_of_checking.rc not in [0, 1] )

- name: Block of creating an OpenStack service
  block:
    - name: Debug print OpenStack service that will be created
      ansible.builtin.debug:
        msg: "Creating an OpenStack service - service_name={{ service_name }}, service_type={{ service_type }}, service_description={{ service_description }}"

    - name: Create an OpenStack service
      ansible.builtin.command:
        argv: ["openstack", "service", "create", "--name", "{{ service_name }}", "--description", "{{ service_description }}", "{{ service_type }}"]
  when: result_of_checking.rc == 0

