---
- name: "Creating pool for Ceph => {{ item }}"
  #ansible.builtin.command: ceph osd pool create {{ item.name }} {{ item.num_of_placement_groups }}
  ansible.builtin.script: ./create_ceph_pool.sh "{{ item.name }}" "{{ item.num_of_placement_groups }}"
  with_items: "{{ group_vars.ceph.pools }}"

