---
- name: "Creating pool for Ceph => {{ item }}"
  # item.key -> name of a pool, item.value -> num of pool
  ansible.builtin.script: ./create_ceph_pool.sh "{{ item.name }}" "{{ item.num_of_placement_groups }}"
  with_items: "{{ group_vars.ceph.pools | dict2items }}"

