---
- name: Copy rules.v4 for iptables
  ansible.builtin.template:
    src: "{{ inventory_hostname }}/rules.v4.j2"
    dest: "/etc/iptables/rules.v4"
    owner: root
    group: root
    mode: '644'
    backup: yes
  when: "'routers' in group_names"
  notify: Restart netfilter-persistent

