---
- name: Declare path of the configuration file
  set_fact:
    group_directory: "{% if 'compute_nodes' in group_names %}compute_nodes{% elif 'private_routers' in group_names %}private_routers{% else %}default{% endif %}"

- name: Create rules.v4 for iptables
  ansible.builtin.template:
    src: "{{ group_directory }}/rules.v4.j2"
    dest: "/etc/iptables/rules.v4"
    owner: root
    group: root
    mode: '644'
    backup: yes
  notify: Restart netfilter persistent

- name: Run notified handler of iptables
  meta: flush_handlers

- name: Iptables should be enabled
  ansible.builtin.systemd:
    name: netfilter-persistent
    enabled: yes

