---
#
# Users and roles are already created at tasks in Keystone
#
- name: Check a flag that means create_service_placement was finished
  stat:
    path: /root/.ansible_placement_service_was_created
  register: flag_file

- name: Create service for Placement
  ansible.builtin.command:
    argv:
      - openstack
      - service
      - create
      - --name
      - "{{ group_vars.placement.service.name }}"
      - --description
      - "{{ group_vars.placement.service.description }}"
      - "{{ group_vars.placement.service.type }}"

- name: Create a flag that means create_service_placement was finished
  copy:
    content: ""
    dest: /root/.ansible_placement_service_was_created
    force: no
    owner: root
    group: root
    mode: '0640'
