---
- name: Install packages for sql services
  apt:
    name:
      - mariadb-server
      - mariadb-client
      - python3-pymysql
  register: apt_result
  retries: 360
  delay: 5
  until: apt_result is success

- name: Configure /etc/mysql/mariadb.conf.d/99-openstack.cnf
  ansible.builtin.template:
    src: 99-openstack.cnf
    dest: /etc/mysql/mariadb.conf.d/99-openstack.cnf
    group: root
    owner: root
    mode: '0644'
  notify: Restart mariadb

- name: Run notified handler of mariadb
  meta: flush_handlers

- name: MariaDB should be enabled
  ansible.builtin.systemd:
    enabled: true
    name: mariadb

# Run mysql_secure_installation if it was not run
- name: Check a flag that means mysql_secure_installation.yml was finished
  stat:
    path: /root/.mysql_secure_installation_has_finished
  register: flag_file

- include_tasks: mysql_secure_installation/main.yml
  when: not flag_file.stat.exists

- name: Create a flag that means mysql_secure_installation.yml was finished
  copy:
    content: ""
    dest: /root/.mysql_secure_installation_has_finished
    force: no
    owner: root
    group: root
    mode: '0640'

