---
- name: Check a flag that means init_glance_db.yml was finished
  stat:
    path: /root/.ansible_glance_database_was_initialized
  register: flag_file

- name: Init glance DB
  block:
    - name: Create Glance database
      ansible.builtin.command:
        argv:
          - mysql
          - -e
          - "CREATE DATABASE glance;"

    - name: Grant privileges to resources on glance database for a user glance at localhost
      ansible.builtin.command:
        argv:
          - mysql
          - -e
          - "GRANT ALL PRIVILEGES ON glance.* TO '{{ group_vars.glance.user }}'@'localhost' IDENTIFIED BY '{{ group_vars.glance.password }}';"

    - name: Grant privileges to resources on glance database for a user glance at remote host
      ansible.builtin.command:
        argv:
          - mysql
          - -e
          - "GRANT ALL PRIVILEGES ON glance.* TO '{{ group_vars.keystone.user }}'@'%' IDENTIFIED BY '{{ group_vars.keystone.password }}';"
  when: not flag_file.stat.exists

- name: Create a flag that means init_glance_database.yml was finished
  copy:
    content: ""
    dest: /root/.ansible_glance_database_was_initialized
    force: no
    owner: root
    group: root
    mode: '0640'

