---
- name: Declare openstack_service_name for glance
  set_fact:
    openstack_service_name: "glance"

- name: Include role-functions to create DB for glance
  include_role:
    name: functions
    tasks_from: create_db/main.yml
