---
# TODO: This instruction supports "access_as_shared" only so far.
#
- name: Declare target_rbac_projects
  set_fact:
    target_rbac_projects: []

- name: Declare a variable of admin project list
  set_fact:
    admin_projects_list: "[{% for item in domain.projects if 'admin' in item.name %}{{ item }}{% if not loop.last %},{% endif %}{% endfor %}]"

- name: Block of declaring target_rbac_projects for admin project if it was not declared in a config
  block:
    - name: Get a list of networks to assign RBACs to admin project
      script: get_list_of_networks.sh
      register: result_of_network_list

    - name: Declare a variables admin_network_list_to_add_rbacs and admin_project_list_to_add_rbacs
      set_fact:
        admin_network_list_to_add_rbacs: []
        admin_project_list_to_add_rbacs: []

    - name: Declare a list of networks for admin to add RBACs
      set_fact:
        admin_network_list_to_add_rbacs: "{{ admin_network_list_to_add_rbacs + [{ 'name': item, 'actions': ['access_as_shared'] }] }}"
      with_items: "{{ result_of_network_list.stdout_lines }}"

    - name: Declare a variable of project for admin to add RBACs
      set_fact:
        admin_project_list_to_add_rbacs: "{{ admin_project_list_to_add_rbacs + [{'name': 'admin', 'rbac': admin_network_list_to_add_rbacs}] }}"

    - name: Declare networks that have RBACs for an admin project
      set_fact:
        target_rbac_projects: "{{ target_rbac_projects + admin_project_list_to_add_rbacs }}"
      when: '(result_of_network_list.stdout_lines | length > 0)'
  when: '(admin_projects_list | length < 1)'

#- name: Create a list in order to add RBAC to admin project in "domain.projects" by default
#  set_fact:
#    target_rbac_projects: '{{ target_rbac_projects }} + {{ domain.projects }}'
#  when: '("admin" not in domain.projects) and (networks_assign_rbac | length < 1)'

- name: Append a projects from a config
  set_fact:
    target_rbac_projects: '{{ target_rbac_projects }} + {{ domain.projects }}'

- name: RBAC access_as_shard will be added in projects below by default(so far).
  ansible.builtin.debug:
    msg: "{% for item in target_rbac_projects %}{{ item.name }}{% if not loop.last %},{% endif %}{% endfor %}"

- name: Include do_create_and_assign_rbac_in_a_project.yml
  include: do_create_and_assign_rbac_in_a_project.yml
  loop_control:
    loop_var: project
  loop: "{{ target_rbac_projects }}"
  # TODO: RBAC access_as_shard will be assigned in all projects so far.
  when:
    - '"rbac" in project'
