---
# Variables
#   rbac_action:
#     A name of action in the RBAC.
#   rbac_domain:
#     A domain that contains its name(domain.name), projects(domain.projects), description(domain.description) etc for RBACs.
#   rbac_project:
#     A project that contains its name and networks for RBACs.
#   rbac_network:
#     A network that contains its name and actions for RBACs.

# TODO: Create and assign Role based Access Control(rbac) to a project.
- name: Print a RBAC that will be added
  ansible.builtin.debug:
    msg: "An information of RBAC will be added: domain.name={{ rbac_domain.name }}, project.name={{ rbac_project.name }}, network.name={{ rbac_network.name }}, action={{ rbac_action }}"

##- name: Add RBAC for the project
##  ansible.builtin.script: ./get_network_id.sh "{{ network }}" "{{ domain.name }}"

