---
# TODO: This instruction supports "access_as_shared" only so far.
#
- name: Declare target_rbac_projects
  set_fact:
    target_rbac_projects: []

- name: Declare a variable of admin project list
  set_fact:
    admin_projects_list: "[{% for item in domain.projects if 'admin' in item.name %}{{ item }}{% if not loop.last %},{% endif %}{% endfor %}]"

- name: Block of declaring target_rbac_projects for admin project if it was not declared in a config
  block:
    - name: Get a list of networks to assign RBACs to admin project
      shell: "openstack network list --format json"
      
      register: result_of_network_list
    - name: Check whether the networks are existed or not
    - name: Declare networks that have RBACs for an admin project
  when: '(admin_projects_list | length < 1)'

#- name: Append interim project for admin into target_rbac_projects in order to add RBAC to it by default
#  set_fact:
#    target_rbac_projects: '{{ target_rbac_projects + [{"name": "admin", "rbac": {"networks": "access_as_shared"}}] }}'
#  when: '(admin_projects_list | length < 1)'

- name: Create a list in order to add RBAC to admin project in "domain.projects" by default
  set_fact:
    target_rbac_projects: '{{ target_rbac_projects }} + {{ domain.projects }}'
  when: '"admin" not in domain.projects'

- name: RBAC access_as_shard will be added in projects below by default(so far).
  ansible.builtin.debug:
    msg: "{% for item in target_rbac_projects %}{{ item.name }}{% if not loop.last %},{% endif %}{% endfor %}"

- name: Include do_create_and_assign_rbac_in_a_project.yml
  include: do_create_and_assign_rbac_in_a_project.yml
  loop_control:
    loop_var: project
  loop: "{{ target_rbac_projects }}"
  # TODO: RBAC access_as_shard will be assigned in all projects so far.
  when:
    - '"rbac" in project'
