---
# Variables
#   a_rbac:
#     A name of
#   domain:
#     A domain that contains its name(domain.name), projects(domain.projects), description(domain.description) etc.
#   project:
#     A project that contains its name and networks for RBAC.
#   network:
#     A network that contains its name and actions of RBAC.

# TODO: Create and assign Role based Access Control(rbac) to a project.
- name: Print a RBAC that will be added
  ansible.builtin.debug:
    msg: "An information of RBAC will be added: domain.name={{ domain.name }}, project.name={{ project.name }}, network.name={{ network.name }}, action={{  }}"

##- name: Add RBAC for the project
##  ansible.builtin.script: ./get_network_id.sh "{{ network }}" "{{ domain.name }}"

# If a return code 1 and the output is "...An RBAC policy already exists with those values.", the instruction should be skipped because the rule is already registerd.

