---
- name: Configure /etc/swift/swift.conf
  ansible.builtin.template:
    src: etc/swift/swift.conf.j2
    dest: /etc/swift/swift.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart rsync
