---
#- name: "Fetch the file \"/etc/ceph/ceph.conf\" from the {{ inventory_hostname }} to push any ceph nodes"
#  run_once: yes
#  fetch:
#    src: "{{ item }}"
#    dest: ".buffer/{{ item | basename }}"
#    flat: yes
#  with_items:
#    - "/etc/ceph/ceph.conf"
#    - "/etc/ceph/ceph.client.admin.keyring"
#    - "/var/lib/ceph/bootstrap-osd/ceph.keyring"

- name: "Fetch the file \"/etc/ceph/ceph.conf\" from the {{ inventory_hostname }} to push any ceph nodes"
  run_once: yes
  fetch:
    src: "{{ item }}"
    dest: ".buffer/{{ item | basename }}"
    flat: yes
  with_items:
    - "/etc/ceph/ceph.conf"
    - "/etc/ceph/ceph.client.admin.keyring"
    - "/var/lib/ceph/bootstrap-osd/ceph.keyring"
    - "/etc/ceph/ceph.client.cinder.keyring"
    - "/etc/ceph/ceph.client.glance.keyring"
    - "/etc/ceph/ceph.client.cinder-backup.keyring"

