---
- name: Install packages of swift node
  apt:
    name:
      # For a filesystem XFS and data sync(rsyncd)
      - xfsprogs
      - rsync
      # For Swift
      - swift
      - swift-account
      - swift-container
      - swift-object
  register: apt_result
  retries: 360
  delay: 5
  until: apt_result is success
