---
- name: Set /etc/neutron/neutron.conf of Neutron with Linux Bridge
  ansible.builtin.template:
    src: computes/neutron/neutron.conf.j2
    dest: /etc/neutron/neutron.conf
    owner: root
    group: neutron
    mode: '0640'
    backup: yes
  notify: ["Restart nova-compute", "Restart neutron-linuxbridge-agent"]
  register: result_neutron_conf

- name: Set /etc/neutron/plugins/ml2/linuxbridge_agent.ini of Neutron with Linux Bridge
  ansible.builtin.template:
    src: computes/neutron/plugins/ml2/linuxbridge_agent.ini.j2
    dest: /etc/neutron/plugins/ml2/linuxbridge_agent.ini
    owner: root
    group: neutron
    mode: '0640'
    backup: yes
  notify: ["Restart nova-compute", "Restart neutron-linuxbridge-agent"]
  register: result_linuxbridge_agent_ini
