---
- name: A block to verify Swift
  block:
    - name: "Run swift stat to verify a Swift"
      command: swift stat
      register: result_of_swift_stat
    
    - name: "Print output of Swift ring-builder"
      ansible.builtin.debug:
        msg: "{{ result_of_swift_stat.stdout.split('\n') }}"
  when: "'controllers' in group_names"
