---
- name: Install packages of Nova
  apt:
    name:
      - nova-api
      - nova-conductor
      - nova-novncproxy
      - nova-scheduler

#- name: Check a flag that means set config and sync db was finished
#  stat:
#    path: /root/.ansible_glance_set_config_and_sync_db_was_finished
#  register: flag_file

- name: Set /etc/nova/nova.conf
  ansible.builtin.template:
    src: glance/glance-api.conf.j2
    dest: /etc/glance/glance-api.conf
    owner: root
    group: glance
    mode: 0640
    backup: yes
  register: template_result

# There are no patterns to detect options to sync DB.
# So they are written as hard coded so far.
- name: Sync database for glance
  ansible.builtin.command:
    argv: ["su", "-s", "/bin/sh", "-c", "{{ item }}", "{{ group_vars.nova.user }}"]
  loop:
    - "nova-manage api_db sync"
    - "nova-manage cell_v2 map_cell0"
    - "nova-manage cell_v2 create_cell --name=cell1 --verbose"
  when: template_result.changed

