---
- name: Install packages of Nova controller node
  apt:
    name:
      - cinder-api
      - cinder-scheduler
  register: apt_result
  retries: 360
  delay: 5
  until: apt_result is success

- name: Enable and start iscsi.service on controller nodes
  ansible.builtin.systemd:
    name: iscsid
    state: started
    enabled: yes
