---
- name: Install packages of Cinder for cinder nodes
  apt:
    name:
      - cinder-volume
      - tgt
    update_cache: yes
  register: apt_result
  retries: 360
  delay: 5
  until: apt_result is success
