---
- name: Add a repository of OpenStack wallaby
  ansible.builtin.apt_repository:
    repo: deb http://ubuntu-cloud.archive.canonical.com/ubuntu focal-updates/wallaby main

- name: Update package indexes
  apt:
    update_cache: yes

- name: Dist-Upgrade packages
  apt:
    upgrade: dist

- name: Install python3-openstackclient
  apt:
    pkg:
      - python3-openstackclient

