---
# This is a file to build Neutron with Linux Bridge.

- name: Block of Neutron with Linux Bridge for controllers
  block:
    - name: Include common/create_dbs/main.yml
      include: common/create_dbs/main.yml

    - name: Include common/create_openstack_services/main.yml
      include: common/create_openstack_services/main.yml

    - name: Include common/create_endpoints/main.yml
      include: common/create_endpoints/main.yml

    - name: Include prepare_ovn/controllers/main.yml
      include: prepare_ovn/controllers/main.yml
  when: "'controllers' in group_names"

- name: Block of Neutron with Linux Bridge for computes
  block:
    - name: Include prepare_ovn/computes/main
      include: prepare_ovn/computes/main.yml
  when: "'computes' in group_names"
