---
# This is a file to build Neutron with Linux Bridge.

- name: Block of Neutron with Linux Bridge for controllers
  block:
    - name: Include common/create_dbs/main.yml
      include: common/create_dbs/main.yml

    - name: Include common/create_openstack_services/main.yml
      include: common/create_openstack_services/main.yml

    - name: Include common/create_endpoints/main.yml
      include: common/create_endpoints/main.yml

    - name: Include prepare_linux_bridge/controllers/install_packages.yml
      include: prepare_linux_bridge/controllers/install_packages.yml

    - name: Include prepare_linux_bridge/controllers/set_sysctl.yml
      include: prepare_linux_bridge/controllers/set_sysctl.yml

    - name: Include prepare_linux_bridge/controllers/set_configurations.yml
      include: prepare_linux_bridge/controllers/set_configurations.yml
  when: "'controllers' in group_names"

- name: Block of Neutron with Linux Bridge for computes
  block:
    - name: Include prepare_linux_bridge/computes/main
      include: prepare_linux_bridge/computes/main.yml
  when: "'computes' in group_names"
