---
# This is a file to build Neutron with Linux Bridge.

- name: Include include_neutron_with_linux_bridge_in_controllers.yml
  include: include_neutron_with_linux_bridge_in_controllers.yml
  when: "'controllers' in group_names"

- name: Include include_neutron_with_linux_bridge_in_controllers.yml
  include: include_neutron_with_linux_bridge_in_computes.yml
  when: "'computes' in group_names"

