---
# This is a file to build Neutron with Linux Bridge.

- name: Block of Neutron with Linux Bridge for controllers
  block:
    - name: Include create_dbs/main.yml
      include: create_dbs/main.yml

    - name: Include create_openstack_services/main.yml
      include: create_openstack_services/main.yml

    - name: Include create_endpoints/main.yml
      include: create_endpoints/main.yml

    - name: Include prepare_linux_bridge/controllers/main.yml
      include: prepare_linux_bridge/controllers/main.yml
  when: "'controllers' in group_names"

- name: Block of Neutron with Linux Bridge for computes
  block:
    - name: Include prepare_linux_bridge/computes/main
      include: prepare_linux_bridge/computes/main.yml
  when: "'computes' in group_names"
