---
- name: Block of Neutron with OVN for controllers
  block:
    - name: Include create_db/main.yml
      include_tasks: create_db/main.yml

    - name: Include create_openstack_services/main.yml
      include_tasks: create_openstack_services/main.yml

    - name: Include create_endpoints/main.yml
      include_tasks: create_endpoints/main.yml

    - name: Include install_packages/ovn/controllers/main.yml
      include_tasks: install_packages/ovn/controllers/main.yml

    - name: Include set_configurations/ovn/controllers/main.yml
      include_tasks: set_configurations/ovn/controllers/main.yml

    - name: Include configure_ovn_interfaces/ovn/controllers/main.yml
      include_tasks: configure_ovn_interfaces/ovn/controllers/main.yml

    - name: Include configure_ovn_db/main.yml
      include_tasks: configure_ovn_db/main.yml

    - name: Check whether the Neutron is running correctly after setting it
      include_tasks: check_neutron_is_running/controllers/main.yml
  when: "'controllers' in group_names"

- name: Block of Neutron with OVN for computes
  block:
    - name: Include install_packages/ovn/computes/main.yml
      include_tasks: install_packages/ovn/computes/main.yml

    - name: Include set_configurations/ovn/computes/main.yml
      include_tasks: set_configurations/ovn/computes/main.yml

    - name: Include configure_ovs_services/computes/main.yml
      include_tasks: configure_ovs_services/computes/main.yml
  when: "'computes' in group_names"
