---
# This is a file to build Neutron with Linux Bridge.

- name: Block of Neutron with Linux Bridge for controllers
  block:
    - name: Include create_db/main.yml
      include_tasks: create_db/main.yml

    - name: Include create_openstack_services/main.yml
      include_tasks: create_openstack_services/main.yml

    - name: Include create_endpoints/main.yml
      include_tasks: create_endpoints/main.yml

    - name: Include install_packages/linux_bridge/controllers/main.yml
      include_tasks: install_packages/linux_bridge/controllers/main.yml

    - name: Include set_sysctl/main.yml
      include_tasks: set_sysctl/main.yml

    - name: Include set_configurations/linux_bridge/controllers/main.yml
      include_tasks: set_configurations/linux_bridge/controllers/main.yml
  when: "'controllers' in group_names"

- name: Block of Neutron with Linux Bridge for computes
  block:
    - name: Include install_packages/linux_bridge/computes/main.yml
      include_tasks: install_packages/linux_bridge/computes/main.yml

    - name: Include set_sysctl/main.yml
      include_tasks: set_sysctl/main.yml

    - name: Include set_configurations/linux_bridge/computes/main.yml
      include_tasks: set_configurations/linux_bridge/computes/main.yml
  when: "'computes' in group_names"
