---
- name: Include create_dbs/main.yml
  include: create_dbs/main.yml

- name: Include create_openstack_services/main.yml
  include: create_openstack_services/main.yml

- name: Include create_endpoints/main.yml
  include: create_endpoints/main.yml

- name: Include prepare_linux_bridge_for_controllers/main.yml
  include: prepare_linux_bridge_for_controllers/main.yml
