---
- name: Determin which network driver will be used
  set_fact:
    network_plugin: "{% if 'network' not in group_vars.openstack or 'plugin' not in group_vars.openstack.network or 'OVN' != group_vars.openstack.network.plugin %}linux_bridge{% else %}ovn{% endif %}"

# For network plugin OVN
- name: Block neutron
  block:
    - name: Include install neutron with plugin OVN
      include: include_install_neutron_with_ovn.yml
      when: "group_vars.openstack.network.plugin == 'OVN'"
    - name:
  when: "'network ' not in group_vars.openstack or 'plugin' not in group_vars.openstack.network"

# For network plugin Linux Bridge
- name: Include install neutron with plugin Linux Bridge
  include: include_install_neutron_with_linux_bridge.yml
  when: "group_vars.openstack.network.plugin != 'OVN'"



