---
- name: Determin which network driver will be used. Linux Bridge or OVN are only supported so far.
  set_fact:
    network_plugin: "{% if 'network' not in group_vars.openstack or 'plugin' not in group_vars.openstack.network or 'Linux Bridge' == group_vars.openstack.network.plugin %}Linux Bridge{% else %}{{ group_vars.openstack.network.plugin }}{% endif %}"

# TODO: Network plugin "OVN" is not supported yet
#- name: Checking type of plugin that is not supported yet
#  ansible.builtin.fail:
#    msg: "Network plugin 'OVN' is not supported currently. It will be supported near future."
#  when: "'OVN' == network_plugin"

- name: Checking detection of Neutron network plugin value
  ansible.builtin.fail:
    msg: "Unknown Neutron network plugin. 'Linux Bridge' or 'OVN' is only allowd in group_vars.openstack.network.plugin. (group_vars.openstack.network.plugin == {{ group_vars.openstack.network.plugin }}) was found."
  when: "'Linux Bridge' != network_plugin and 'OVN' != network_plugin"

# Configure network plugin for Linux Bridge
- name: Include include_neutron_with_linux_bridge.yml
  include_tasks: include_neutron_with_linux_bridge.yml
  when: "'Linux Bridge' == network_plugin"

# Configure network plugin for OVN
- name: Include include_neutron_with_ovn.yml
  include_tasks: include_neutron_with_ovn.yml
  when: "'OVN' == network_plugin"

- name: Run notified handlers of Neutron OVN
  meta: flush_handlers

