---
- name: Print endpoint that will be created
  ansible.builtin.debug:
    msg: "scope={{ scope }}, region={{ region.name }}, type_of_endpoint={{ type_of_endpoint }}, url={{ region.url }}"

- name: Get list of projects
  ansible.builtin.command:
    argv:
      - openstack
      - endpoint
      - create
      - --region
      - "{{ region.name }}"
      - "{{ type_of_endpoint }}"
      - "{{ scope }}"
      - "{{ region.url }}"
  register: result

- name: Print the result of creating an endpoint
  ansible.builtin.debug:
    msg: "{{ result.stdout.split('\n') }}"

