---
#
# "create_roles" is a task to create endpoints for each services.
# It requires variables like below.
#
# * endpoint (converted to item from type dictionary)
#   A variable contains information how end point should be created.
#   It might contains some information about scope(public or internal or admin) and regions.
#   This variable must be equals as "group_vars.<component>.endpoints.<key of scope> == endpoint.key" and "group_vars.<component>.endpoints.<scope>.regions == endpoint.value.regions" 
#   // eg) group_vars.glance.endpoints
#
# * type_of_endpoint (type string)
#   A variable for type of endpoint.
#   // eg) "image", "placement" etc...
#
#   This tasks assumes be included like below.
#   ```
#   - name: Declare type_of_endpoint to include a tasks create_endpoint in function role
#
#   - name: Include create_endpoint/main in a role functions
#     include_role:
#       name: functions
#       tasks_from: create_endpoint/main.yml
#     loop_control:
#       loop_var: endpoint
#     loop: "{{ group_vars.glance.endpoints | dict2items }}"
#   ```
#

#- name: Debug values
#  ansible.builtin.debug:
#    msg: "endpoint.key={{ endpoint.key }}, endpoint.value={{ endpoint.value }}"

- name: Declare variables scope_of_endpoint, regions
  set_fact:
    scope: "{{ endpoint.key }}"
    regions: "{{ endpoint.value.regions }}"

- name: Include do_create_endpoint.yml
  include_role:
    name: functions
    tasks_from: create_endpoint/do_create_endpoint.yml
  loop_control:
    loop_var: region
  loop: "{{ regions }}"



#- name: Include do_create_endpoint.yml
#  include: do_create_endpoint.yml
#  loop_control:
#    loop_var: region
#  loop: "{{ regions }}"

