---
#
# "create_roles" is a task to create endpoints for each services.
# It requires variables like below.
#
# * openstack_service_name (type String)
#   A service name of OpenStack service. eg) "glance", "placement" etc.
#   Values of endpoints will be used from group_vars in each OpenStack services.
#   For example, if you specified the value as "glance", configurations of endpoints under "group_vars.glance.endpoints.endpoints" will be used.
#
#   This tasks is assumed to be included like below.
#   ```
#   - name: Include role-functions to create endpoints for glance
#     include_role:
#       name: functions
#       tasks_from: create_endpoint/main.yml
#     vars:
#       openstack_service_name: "glance"
#   ```

- name: Include create_endpoint/create_endpoint.yml in function role
  include_role:
    name: functions
    tasks_from: create_endpoint/create_endpoint.yml
  loop_control:
    loop_var: service_interface
  loop: ["public", "internal", "admin"]
