- name: Install packages of Neutron for controllers of Neutron with Linux Bridge
  apt:
    name:
      - neutron-server
      - neutron-plugin-ml2
      - neutron-linuxbridge-agent
      - neutron-l3-agent
      - neutron-dhcp-agent
      - neutron-metadata-agent
      - neutron-fwaas-common
  register: apt_result
  retries: 360
  delay: 5
  until: apt_result is success
