---
- name: Set /etc/neutron/neutron.conf of Neutron with OVN on controller
  ansible.builtin.template:
    src: neutron/neutron.conf.j2
    dest: /etc/neutron/neutron.conf
    owner: root
    group: neutron
    mode: '0640'
    backup: yes
  notify: ["Restart ovsdb-server", "Restart ovn-ovsdb-server-nb", "Restart ovn-ovsdb-server-sb", "Restart neutron-server", "Restart openvswitch-switch", "Migrate neutron db for ovn", "Restart ovn-central", "Restart ovn-northd"]

- name: Set /etc/neutron/l3_agent.ini of Neutron with OVN
  ansible.builtin.template:
    src: neutron/l3_agent.ini.j2
    dest: /etc/neutron/l3_agent.ini
    owner: root
    group: neutron
    mode: '0640'
    backup: yes
  notify: ["Restart ovsdb-server", "Restart ovn-ovsdb-server-nb", "Restart ovn-ovsdb-server-sb", "Restart neutron-server", "Restart openvswitch-switch"]

- name: Set /etc/neutron/plugins/ml2/ml2_conf.ini of Neutron with OVN on controller
  ansible.builtin.template:
    src: neutron/plugins/ml2/ml2_conf.ini.j2
    dest: /etc/neutron/plugins/ml2/ml2_conf.ini
    owner: root
    group: neutron
    mode: '0640'
    backup: yes
  notify: ["Restart ovsdb-server", "Restart ovn-ovsdb-server-nb", "Restart ovn-ovsdb-server-sb", "Restart neutron-server", "Restart openvswitch-switch", "Migrate neutron db for ovn", "Restart ovn-central", "Restart ovn-northd"]

- name: Set /etc/default/openvswitch-switch of Neutron with OVN on controller
  ansible.builtin.template:
    src: default/openvswitch-switch
    dest: /etc/default/openvswitch-switch
    owner: root
    group: root
    mode: '0644'
    backup: yes
  notify: ["Restart ovsdb-server", "Restart ovn-ovsdb-server-nb", "Restart ovn-ovsdb-server-sb", "Restart neutron-server", "Restart openvswitch-switch"]

#- name: Flush handlers of Neutron for OVN
#  meta: flush_handlers

# # TODO: 
- name: Reboot OS after configure ovn
  ansible.builtin.reboot:

