---
- name: Set /etc/neutron/neutron.conf of Neutron with OVN on controller
  ansible.builtin.template:
    src: neutron/neutron.conf.j2
    dest: /etc/neutron/neutron.conf
    owner: root
    group: neutron
    mode: '0640'
    backup: yes
  notify: ["Migrate neutron db for ovn", "Reboot OS"]

- name: Set /etc/neutron/l3_agent.ini of Neutron with OVN
  ansible.builtin.template:
    src: neutron/l3_agent.ini.j2
    dest: /etc/neutron/l3_agent.ini
    owner: root
    group: neutron
    mode: '0640'
    backup: yes
  notify: ["Reboot OS"]

- name: Set /etc/neutron/plugins/ml2/ml2_conf.ini of Neutron with OVN on controller
  ansible.builtin.template:
    src: neutron/plugins/ml2/ml2_conf.ini.j2
    dest: /etc/neutron/plugins/ml2/ml2_conf.ini
    owner: root
    group: neutron
    mode: '0640'
    backup: yes
  notify: ["Migrate neutron db for ovn", "Reboot OS"]

- name: Set /etc/default/openvswitch-switch of Neutron with OVN on controller
  ansible.builtin.template:
    src: default/openvswitch-switch
    dest: /etc/default/openvswitch-switch
    owner: root
    group: root
    mode: '0644'
    backup: yes
  notify: ["Reboot OS"]

- name: Flush handlers of Neutron for OVN
  meta: flush_handlers

