---
- name: Get the existence of a directory /etc/cloud/cloud.cfg.d
  stat:
    path: /etc/cloud/cloud.cfg.d
  register: stat_directory

- name: Get the existence of a file /etc/cloud/cloud.cfg.d
  stat:
    path: /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg
  register: stat_file

- name: Create a file if /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg was not existed
  copy:
    dest: "/etc/cloud/cloud.cfg.d/99-disable-network-config.cfg"
    content: "network: {config: disabled}"
  when: "stat_directory.stat.exists and not stat_file.stat.exists"

- name: Declare path of the configuration file
  set_fact:
    group_directory: "{% if 'compute_nodes' in group_names %}compute_nodes{% elif 'private_routers' in group_names %}private_routers{% else %}default{% endif %}"

- name: Debug group_names
  ansible.builtin.debug:
    msg: "group_names={{ group_names }}, groups={{ groups }}, group_directory={{ group_directory }}"

- name: Clean a directory /etc/netplan
  shell: "find /etc/netplan -type f -not -name 90-custom-network-config.yaml -delete"

- name: Create 90-custom-network-config.yaml for netplan
  ansible.builtin.template:
    src: "{{ group_directory }}/90-custom-network-config.yaml.j2"
    dest: "/etc/netplan/90-custom-network-config.yaml"
    owner: root
    group: root
    mode: '0644'
    backup: no
  notify: Reboot machine

