---
- name: Create 00-installer-config.yaml for netplan
  ansible.builtin.template:
    src: "{{ inventory_hostname }}/00-installer-config.yaml.j2"
    dest: "/etc/netplan/00-installer-config.yaml"
    owner: root
    group: root
    mode: '644'
    backup: no
  notify: Apply netplan
