---
- name: Declare template directory of the nova.conf
  set_fact:
    group_directory: "{% if 'controllers' in group_names %}controllers{% else %}default{% endif %}"

- name: Set /etc/nova/nova.conf
  ansible.builtin.template:
    src: "{{ group_directory }}/nova.conf.j2"
    dest: /etc/nova/nova.conf
    owner: root
    group: nova
    mode: 0640
    backup: yes
  register: template_result

- name: Include sync_db_for_nova_controllers.yml
  include: sync_db_for_nova_controllers.yml
  when: "'controllers' in group_names"

- name: Include sync_db_for_nova_computes.yml
  include: sync_db_for_nova_computes.yml
  when: "'computes' in group_names"

