---
# These instructions assumes that a variable "template_result" that containing the result of the editing nova.conf was already declared.

- name: Check a flag that means setting config and syncing db for Nova computes was finished
  stat:
    path: /root/.ansible_sync_db_for_nova_computes_was_finished
  register: flag_file

- name: Restart services for Nova computes
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - nova-api
  when: template_result.changed

- name: Block of sync DB for Nova compute nodes
  block:
    - name: Sync Nova database for compute nodes
      ansible.builtin.command:
        argv: ["su", "-s", "/bin/sh", "-c", "nova-manage cell_v2 discover_hosts --verbose", "nova"]
      register: result

    - name: Print the result of syncing Nova DB for compute nodes
      ansible.builtin.debug:
        msg: "{{ result.stdout.split('\n') }}"
  when: not flag_file.stat.exists and 'computes' in group_names

- name: Create a flag that means setting config and syncing db for Nova controllers was finished
  copy:
    content: ""
    dest: /root/.ansible_sync_db_for_nova_computes_was_finished
    force: no
    owner: root
    group: root
    mode: '0640'

- name: Restart services for Nova computes
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - nova-api
  when: template_result.changed

