# This instruction assumes a variable `flavor` was already declared.
#   flavor.id:
#     Id of the flavor
#   flavor.name:
#     Flavor name that will be created
#   flavor.ram
#     Size of ram that the flavor will equip.
#   flavor.disk:
#     Size of disk that the flavor will equip.
#   flavor.vcpus:
#     Num of vcpus that the flavor will equip.

- name: Print a flavor that will be created in this section
  ansible.builtin.debug:
    msg: "loop_index -> \"{{ ansible_loop.index }}\", flavor.id == \"{{ flavor.id }}\", flavor.name == \"{{ flavor.name }}\", flavor.ram == \"{{ flavor.ram }}\", flavor.disk == \"{{ flavor.disk }}\", flavor.vcpus == \"{{ flavor.vcpus }}\""

- name: Check the flavor has already existed or not
  ansible.builtin.script: ./check_duplicate_flavor.sh "{{ flavor.name }}"
  register: result_of_checking_flavor
  failed_when: result_of_checking_flavor.rc not in [0, 1]

- name: Create a flavor
  ansible.builtin.command:
    argv: ["openstack", "flavor", "create", "--id", "{{ flavor.id }}", "--ram", "{{ flavor.ram }}", "--disk", "{{ flavor.disk }}", "--vcpus", "{{ flavor.vcpus }}", "{{ flavor.name }}"]
  when: result_of_checking_flavor.rc == 0

