---
- name: Install packages for etcd
  apt:
    name:
      - etcd

- name: Get IP address from a hostname
  ansible.builtin.shell:
    cmd: getent hosts {{ inventory_hostname }} | cut -d ' ' -f 1
  register: ret_getent

- name: Declare a variable for IP address
  set_fact:
    ip_of_inventory_host: "{{ ret_getent.stdout_lines[0] }}"

- name: Create etcd config file
  ansible.builtin.template:
    src: etcd.j2
    dest: /etc/default/etcd
    owner: root
    group: root
    mode: '0644'
  notify: Restart etcd

- name: Run notified handler of etcd
  meta: flush_handlers

- name: etcd should be enabled
  ansible.builtin.systemd:
    enabled: yes
    name: etcd

