---
- name: Set /etc/nova/nova.conf for computes
  ansible.builtin.template:
    src: nova/nova.conf.j2
    dest: /etc/nova/nova.conf
    owner: root
    group: nova
    mode: 0640
    backup: yes
  notify:
    - Restart nova-compute

- name: Run notified handlers of Nova for computes
  meta: flush_handlers
