---
- name: Install packages of Neutron for computes with OVN
  apt:
    name:
      - neutron-common
      - neutron-plugin-ml2
      - neutron-ovn-metadata-agent
      - ovn-host
      - openvswitch-switch
    update_cache: yes
  register: apt_result
  retries: 360
  delay: 5
  until: apt_result is success
