---
# Parameters
#   client_credentials:
#     A dict of client credentials.
#
#   clent_credentials.key:
#     A name of a credential to create for Ceph.
#
#   client_credentials.value.path:
#     A path of keyring for Ceph.
#
#   client_credentials.value.permission_of_mon:
#     A filter-text of a permission of mon for Ceph.
#

# It assumes that a variable "client_credentials" has already declared.
- name: "Run create_ceph_auth_cap.sh for addming a filter cap."
  ansible.builtin.script: ./create_ceph_auth_cap.sh "{{ item.key }}" "{{ item.value.permission_of_mon }}, allow command \"osd blacklist\"" "{{ item.value.permission_of_osd }}"
  with_items: "{{ client_credentials | dict2items }}"

