---
- name: Detect IP address from a first controller node in hosts
  set_fact:
    controller_ip: "{{ (group_vars.hosts.controllers|selectattr('names', 'contains', inventory_hostname)|first).management.ip }}"

# In a controller node, this instruction will detect an own IP address and set it as OVN controller
- name: Fail if the instruction could not detect an IP of a controller
  fail:
    msg: "Failed to detect an IP of the controller node. There are no same host between \"group_vars\" and \"inventory_hostname\"."
  when: controller_ip | length == 0

- name: Controller IP has detected
  ansible.builtin.debug:
    msg: "controller_ip=\"{{ controller_ip }}\""

# The command "ovn-nbctl set-connection" can be run duplicately.
# If you run this command duplicately, the config will be overwritten by the command that runs last.
# You can run the command "ovn-nbctl get-connection" if you want to see connections that already registered.
- name: Set a connection to Northbound DB for OVN
  ansible.builtin.command:
    argv: ["ovn-nbctl", "set-connection", "ptcp:6641:{{ controller_ip }}", "--", "set", "connection", ".", "inactivity_probe=60000"]

# The command "ovn-sbctl set-connection" can be run duplicately.
# If you run this command duplicately, the config will be overwritten by the command that runs last.
# You can run the command "ovn-sbctl get-connection" if you want to see connections that already registered.
- name: Set a connection to Southbound DB for OVN
  ansible.builtin.command:
    argv: ["ovn-sbctl", "set-connection", "ptcp:6642:{{ controller_ip }}", "--", "set", "connection", ".", "inactivity_probe=60000"]

# FIXME: This instruction has possibility that the multi remotes will be registered if the command run multiply with different controller IP.
# To be more safely, this instruction should only be run if remote was not registered yet.
- name: Add remote Open vSwitch daemon
  ansible.builtin.command:
    argv: ["ovs-appctl", "-t", "ovsdb-server", "ovsdb-server/add-remote", "ptcp:6640:{{ controller_ip }}"]

- name: Restart ovn-northd
  ansible.builtin.systemd:
    state: restarted
    name: ovn-northd
