---
- name: Declare openstack_service_name for placment
  set_fact:
    openstack_service_name: "placement"

- name: Include role-functions to create DB for placement
  include_role:
    name: functions
    tasks_from: create_db/main.yml
