---
- name: Block of test_env
  block:
    - name: Include create_example_cirros/main.yml to create test environment
      include: create_example_cirros/main.yml

    - name: Include create_example_segment/main.yml to create test environment
      include: create_example_segment/main.yml
  when: group_vars.openstack.examples.images.cirros.create == true
