---
- name: Block of test_env
  block:
    - name: Include create_example_cirros/main.yml to create test environment
      include: create_example_cirros/main.yml

    - name: Include create_example_network/main.yml to create test environment
      include: create_example_network/main.yml

    - name: Include create_example_subnet/main.yml to create test environment
      include: create_example_subnet/main.yml

    - name: Include create_example_router/main.yml to create test environment
      include: create_example_router/main.yml
  when: group_vars.openstack.examples.images.cirros.create == true
