---
# "Create_swift_ring" is a task to create rings for Swift.
# It requires variables like below.
# * type_of_builder (type String)
#   A type of builder for Swift. 
#   Accepted values are "account.builder", "container.builder", "object.builder".
#
