---
- name: "Declare an empty variable \"options_of_computes_should_be_registered\""
  set_fact:
    options_of_computes_should_be_registered: []

- name: "Declare list of hosts in \"computes\" to add them to cells"
  set_fact:
    options_of_computes_should_be_registered: "{{ options_of_computes_should_be_registered + [\"-h\", tmp_compute.name] }}"
  loop_control:
    loop_var: tmp_compute
  with_items: "{{ group_vars.hosts.computes }}"

- name: "Declare list of hosts in \"comstorages\" to add them to cells"
  set_fact:
    options_of_computes_should_be_registered: "{{ options_of_computes_should_be_registered + [\"-h\", tmp_compute.name] }}"
  loop_control:
    loop_var: tmp_compute
  with_items: "{{ group_vars.hosts.comstorages }}"



#- name: Discover compute hosts in nova
#  ansible.builtin.command:
#    argv: ['su', '-s', '/bin/sh', '-c', 'nova-manage cell_v2 discover_hosts --verbose', 'nova']
