---
- name: Install packages of Nova controller node
  apt:
    name:
      - nova-api
      - nova-conductor
      - nova-novncproxy
      - nova-scheduler
  when: "'controllers' in group_names"

- name: Install packages of Nova compute node
  apt:
    name:
      - nova-compute
  when: "'computes' not in group_names"
