---
#- name: "Setting permission of the directory /etc/swift"
#  ansible.builtin.file:
#    path: "/etc/swift"
#    owner: root
#    group: swift
#    state: directory
#    recurse: yes

- name: "Setting permission of the directory /etc/swift"
  command: chown -R root:swift /etc/swift

#- name: "Setting permission of the directory {{ destination_of_storage_mount_point }}"
#  ansible.builtin.file:
#    path: "{{ destination_of_storage_mount_point }}"
#    owner: swift
#    group: swift
#    state: directory

- name: "Setting permission of the directory {{ destination_of_storage_mount_point }}"
  command: chown -R swift:swift {{ group_vars.swift.base_mount_point }}

#- name: "Create a directory /var/cache/swift if it does not exist."
#  ansible.builtin.file:
#    path: "/var/cache/swift"
#    owner: root
#    group: swift
#    state: directory
#    mode: '0775'
#    recurse: yes

- name: "Create a directory /var/cache/swift if it does not exist."
  command: chmod -R 755 /var/cache/swift
