---
# Variable info:
#   "item" equals an item in "group_vars.openstack.roles[]"

- name: Check the role is already existed or not
  ansible.builtin.script: ./check_duplicate_role.sh "{{ item.name }}"
  register: result_of_checking
  failed_when: ( result_of_checking.rc not in [0, 1] )

- name: Create a role
  ansible.builtin.command:
    argv: ["openstack", "role", "create", "{{ item.name }}"]
  register: result
  when: result_of_checking.rc == 0

- name: Print the result of creating a role
  ansible.builtin.debug:
    msg: "{{ result.stdout.split('\n') }}"
  when: result_of_checking.rc == 0

- name: Include do_assign_role.yml
  include_tasks: do_assign_role.yml
  loop_control:
    loop_var: inner_item
  loop: "{{ item.assigners }}"

- name: List assigned_roles
  ansible.builtin.command:
    argv: ["openstack", "role", "assignment", "list", "--name"]
  register: result

- name: Print the result of assigned roles
  ansible.builtin.debug:
    msg: "{{ result.stdout.split('\n') }}"

