---
- name: Declare iso file image name
  set_fact:
    iso_cirros_file_name: "{{ group_vars.openstack.examples.images.cirros.image_url.split('/')[-1] }}"

- name: Declare iso file path
  set_fact:
    iso_cirros_file_path: "/root/{{ iso_cirros_file_name }}"

- name: Check an iso file of cirros has already downloaded
  stat:
    path: "{{ iso_cirros_file_path }}"
  register: flag_file

- name: Download cirros image (timeout == 300 sec, retries == 3)
  get_url:
    url: "{{ group_vars.openstack.examples.images.cirros.image_url }}"
    dest: "{{ iso_cirros_file_path }}"
    timeout: 300
  retries: 3
  delay: 2
  when: not flag_file.stat.exists

- name: Check Glance example image of cirros has already created
  ansible.builtin.script: ./check_duplicate_glance_image.sh cirros
  register: result_of_checking
  failed_when: ( result_of_checking.rc not in [0, 1] )

- name: Block of create Glance image of cirros
  block: 
    - name: Create Glance image of cirros
      ansible.builtin.command:
        argv: ["glance", "image-create", "--name", "cirros", "--file", "{{ iso_cirros_file_path }}", "--disk-format", "qcow2", "--container-format", "bare", "--visibility", "public"]
    - name: List Glance images
      ansible.builtin.command:
        argv: ["glance", "image-list"]
      register: result
    - name: Print the result of creating Glance image
      ansible.builtin.debug:
        msg: "{{ result.stdout.split('\n') }}"
  when: result_of_checking.rc == 0
