---
- name: Declare iso file image name
  set_fact:
    iso_cirros_file_name: "{{ group_vars.openstack.examples.images[0].url.split('/')[-1] }}"

- name: Declare iso file path
  set_fact:
    iso_cirros_file_path: "/root/{{ iso_cirros_file_name }}"

- name: Check an iso file of cirros has already downloaded
  stat:
    path: "{{ iso_cirros_file_path }}"
  register: flag_file

- name: Download cirros image (timeout == 300 sec, retries == 3)
  get_url:
    url: "{{ group_vars.openstack.examples.images[0].url }}"
    dest: "{{ iso_cirros_file_path }}"
    timeout: 300
  retries: 3
  delay: 2
  when: not flag_file.stat.exists

- name: Check Glance example image of cirros has already created
  ansible.builtin.script: ./check_duplicate_glance_image.sh "{{ group_vars.openstack.examples.images[0].name }}"
  register: result_of_checking
  failed_when: ( result_of_checking.rc not in [0, 1] )

- name: Block of create Glance image of cirros
  block: 
    - name: Create Glance image of cirros
      ansible.builtin.command:
        argv: ["openstack", "image", "create", "--disk-format", "qcow2", "--container-format", "bare", "--public", "--file", "{{ iso_cirros_file_path }}", "{{ group_vars.openstack.examples.images[0].name }}"]

    - name: List Glance images
      ansible.builtin.command:
        argv: ["openstack", "image", "list"]
      register: result

    - name: Print the result of creating Glance image
      ansible.builtin.debug:
        msg: "{{ result.stdout.split('\n') }}"
  when: result_of_checking.rc == 0

- name: Check whether the instance is already declared or not
  ansible.builtin.script: ./check_duplicate_glance_image.sh cirros
  register: result_check_instance
  failed_when: (result_check_instance.rc not in [0, 1])

- name: Block of creating an instance
  block:
    - name: Print an instance that will be created
      ansible.builtin.debug:
        msg: "instance_name={{ group_vars.openstack.examples.instances[0].name }}, image={{ group_vars.openstack.examples.instances[0].image.name }}, network={{ group_vars.openstack.examples.instances[0].network }}"

    #- name: Create an instance
    #  ansible.builtin.command:
    #    argv: ["openstack", "server", "create", "--flavor", "{{ group_vars.openstack.examples.instances[0].flavor }}", "--image", "{{ group_vars.openstack.examples.instances[0].image.name }}", "--network", "{{ group_vars.openstack.examples.instances[0].network }}", "{{ group_vars.openstack.examples.instances[0].name }}"]

    #- name: Get an instance list after new one was created
    #  ansible.builtin.command:
    #    argv: ["openstack", "server", "list"]
    #  register: result_get_an_instance_list

    #- name: Print an instance list after new one was created
    #  ansible.builtin.debug:
    #    msg: "{{ result_get_an_instance_list.stdout.split('\n') }}"
  when: result_check_instance.rc == 0

