---
- name: Include do_create_image.yml
  include: do_create_image.yml
  loop_control:
    loop_var: image
  loop: '{{ group_vars.openstack.examples.images }}'

- name: Include do_create_instance.yml
  include: do_create_instance.yml
  loop_control:
    loop_var: instance
  loop: '{{ group_vars.openstack.examples.instances }}'


