---
- name: Set /etc/neutron/neutron.conf of Neutron with OVN on compute
  ansible.builtin.template:
    src: neutron/neutron.conf.j2
    dest: /etc/neutron/neutron.conf
    owner: root
    group: neutron
    mode: '0640'
    backup: yes
  notify: ["Restart openvswitch-switch", "Restart ovn-controller", "Restart ovn-host"]
  register: result_neutron_conf

- name: Set /etc/neutron/plugins/ml2/ml2_conf.ini of Neutron with OVN on compute
  ansible.builtin.template:
    src: neutron/ml2_conf.ini
    dest: /etc/neutron/plugins/ml2/ml2_conf.ini
    owner: root
    group: neutron
    mode: '0640'
    backup: yes
  notify: ["Restart openvswitch-switch", "Restart ovn-controller", "Restart ovn-host"]
  register: result_neutron_conf

- name: Set /etc/neutron/neutron_ovn_metadata_agent.ini of Neutron with OVN on compute
  ansible.builtin.template:
    src: neutron/neutron_ovn_metadata_agent.ini
    dest: /etc/neutron/neutron_ovn_metadata_agent.ini
    owner: root
    group: neutron
    mode: '0640'
    backup: yes
  notify: ["Restart openvswitch-switch", "Restart ovn-controller", "Restart ovn-host"]
  register: result_neutron_conf

# TODO: Restart some services

