---
- name: A block for OpenStack Compute service
  block:
    - name: Include init_compute_service_db/main.yml
      include: init_compute_service_db/main.yml
    - name: Include init_nova_service/main.yml
      include: init_nova_service/main.yml


#- name: A block for OpenStack Compute nodes
#  block:


