---
- name: Get LVM volumes for Cinder
  ansible.builtin.script: ./create_lvm_filter_string.sh
  register: result_lvm_filter_string

- name: Configure filter for LVM volumes
  set_fact:
    lvm_filter_string: "{{ result_lvm_filter_string.stdout_lines[-1] }}"
