---
- name: "Run get_backup_swift_url.sh"
  ansible.builtin.script: ./get_backup_swift_url.sh
  register: result_get_backup_swift_url

- name: "Declare backup_swift_url to configure Cinder"
  set_fact:
    backup_swift_url: "{{ result_get_backup_swift_url.stdout_lines[-1] }}"

