- name: Restart memcached
  ansible.builtin.systemd:
    state: restarted
    name: memcached
  retries: 32
  delay: 3

- name: Restart swift-proxy
  ansible.builtin.systemd:
    state: restarted
    name: swift-proxy

- name: Restart rsync
  ansible.builtin.systemd:
    state: restarted
    name: rsync
