---
# Create example subnet

# Create external network list for identifying a subnet was declared as external.
- name: Create a list of network that specified as external
  set_fact:
    external_network_list: "[{% for item in group_vars.openstack.examples.networks if 'external' in item and item.external == True %}'{{ item.name }}'{% if not loop.last %},{% endif %}{% endfor %}]"

- name: Debug external_network_list
  ansible.builtin.debug:
    msg: "external_network_list=={{ external_network_list }}"

- name: Include do_create_subnet.yml
  include: do_create_subnet.yml
  loop_control:
    loop_var: subnet
  loop: "{{ group_vars.openstack.examples.subnets }}"
