---
- name: Install packages of swift-proxy node
  apt:
    name:
      - swift
      - swift-proxy
      - python3-swiftclient
      - python3-keystoneclient
      - python3-keystonemiddleware
      - memcached
