---
# Variables
# * name_of_ring
# * name_of_controller_node

- name: "Sync pull a file {{ name_of_ring }}.ring.gz from {{ name_of_controller_node }} to {{ inventory_hostname }}"
  hosts: "{{ name_of_controller_node }}"
  user: swift
  tasks:
    - name: "Copy the file {{ name_of_ring }}.ring.gz from {{ name_of_controller_node }} to {{ inventory_hostname }}"
      tags: sync-pull
      synchronize:
        src: "/etc/swift/{{ name_of_ring }}.ring.gz"
        dest: "/etc/swift/{{ name_of_ring }}.ring.gz"
        mode: pull
      delegate_to: "{{ inventory_hostname }}"
      register: syncfile
      run_once: true
      with_items:
       - "account"
       - "container"
       - "object"

