- name: Upgrade all current packages
  apt:
    upgrade: full

- name: Check reboot was required
  stat:
    path: /var/run/reboot-required
  register: file_reboot_required

- name: Reboot machine if required
  reboot:
  when: file_reboot_required.stat.exists
