- name: Upgrade all current packages
  apt:
    upgrade: full
    update_cache: yes
  register: apt_result
  retries: 360
  delay: 5
  until: apt_result is success

- name: Install common packages
  apt:
    name:
      - jq
  retries: 360
  delay: 5
  until: apt_result is success

- name: Check reboot was required
  stat:
    path: /var/run/reboot-required
  register: file_reboot_required

- name: Reboot machine if required
  reboot:
  when: file_reboot_required.stat.exists
