- name: Set Apt Cache NG
  ansible.builtin.template:
    src: apt.conf.d/01proxy.j2
    dest: /etc/apt/apt.conf.d
    owner: root
    group: root
    mode: '0644'
  when: group_vars.apt_cache_ng.url is defined

- name: Upgrade all current packages
  apt:
    upgrade: full
    update_cache: yes

- name: Install common packages
  apt:
    name:
      - jq

- name: Check reboot was required
  stat:
    path: /var/run/reboot-required
  register: file_reboot_required

- name: Reboot machine if required
  reboot:
  when: file_reboot_required.stat.exists
