- name: Upgrade all current packages
  apt:
    upgrade: full
    update_cache: yes
  register: apt_result
  retries: 360
  delay: 5
  until: apt_result is success
  timeout: 600

- name: Install common packages
  apt:
    name:
      - jq
  retries: 360
  delay: 5
  until: apt_result is success

- name: Check reboot was required
  stat:
    path: /var/run/reboot-required
  register: file_reboot_required

- name: Reboot machine if required
  reboot:
  when: file_reboot_required.stat.exists

- name: Ensures /opt/getoptses directory exists for getoptses.sh
  file:
    path: /opt/getoptses
    state: directory
    owner: root
    group: root
    mode: '0755'

# Copy a script cloned at https://github.com/TsutomuNakamura/getoptses
- name: Prepare getoptses.sh
  ansible.builtin.copy:
    src: getoptses.sh
    dest: /opt/getoptses/getoptses.sh
    owner: root
    group: root
    mode: '0644'
