---
- name: Restart nova-compute
  ansible.builtin.systemd:
    state: restarted
    name: nova-compute

- name: Restart neutron-linuxbridge-agent
  ansible.builtin.systemd:
    state: restarted
    name: neutron-linuxbridge-agent

