---
# Neutron for controller node
- name: Restart nova-api
  ansible.builtin.systemd:
    state: restarted
    name: nova-api

- name: Restart neutron-server
  ansible.builtin.systemd:
    state: restarted
    name: neutron-server

- name: Restart neutron-linuxbridge-agent
  ansible.builtin.systemd:
    state: restarted
    name: neutron-linuxbridge-agent

- name: Restart neutron-dhcp-agent
  ansible.builtin.systemd:
    state: restarted
    name: neutron-dhcp-agent

- name: Restart neutron-metadata-agent
  ansible.builtin.systemd:
    state: restarted
    name: neutron-metadata-agent

- name: Restart neutron-l3-agent
  ansible.builtin.systemd:
    state: restarted
    name: neutron-l3-agent

# Neutron for compute node
- name: Restart nova-compute
  ansible.builtin.systemd:
    state: restarted
    name: nova-compute

# - Daemons for OVN of controller node ----------------------------------
- name: Restart ovsdb-server
  ansible.builtin.systemd:
    state: restarted
    name: ovsdb-server

- name: Restart ovn-ovsdb-server-ic-nb
  ansible.builtin.systemd:
    state: restarted
    name: ovn-ovsdb-server-ic-nb

- name: Restart ovn-ovsdb-server-ic-sb
  ansible.builtin.systemd:
    state: restarted
    name: ovn-ovsdb-server-ic-sb

- name: Restart ovn-ovsdb-server-nb
  ansible.builtin.systemd:
    state: restarted
    name: ovn-ovsdb-server-nb

- name: Restart ovn-ovsdb-server-sb
  ansible.builtin.systemd:
    state: restarted
    name: ovn-ovsdb-server-sb

- name: Restart neutron-server
  ansible.builtin.systemd:
    state: restarted
    name: neutron-server

# - Daemons for OVN of compute node ----------------------------------
- name: Restart ovn-controller
  ansible.builtin.systemd:
    state: restarted
    name: ovn-controller

- name: Restart openvswitch-switch
  ansible.builtin.systemd:
    state: restarted
    name: openvswitch-switch

- name: Restart ovn-host
  ansible.builtin.systemd:
    state: restarted
    name: ovn-host

- name: Restart neutron-ovn-metadata-agent
  ansible.builtin.systemd:
    state: restarted
    name: neutron-ovn-metadata-agent

# - Migrate DB for neutron -------------------------------------------
- name: Migrate neutron db for ovn
  ansible.builtin.command:
    argv: ["su", "-s", "/bin/sh", "-c", "neutron-db-manage --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/ml2_conf.ini upgrade head", "neutron"]

