---
- name: Restart nova-api
  ansible.builtin.systemd:
    state: restarted
    name: nova-api

- name: Restart cinder-scheduler
  ansible.builtin.systemd:
    state: restarted
    name: cinder-scheduler

- name: Restart apache2
  ansible.builtin.systemd:
    state: restarted
    name: apache2
