---
host_vars:
  iptables:
    provider:
      nat:
        src: 192.168.1.0/24

  network:
    provider:
      bridge:
        - name: br0
          ip: 192.168.1.254/24
          gateway4: 192.168.1.1
          mtu: 1500
          nameservers:
            addresses:
              - 192.168.1.1
              - 8.8.8.8
              - 8.8.4.4
    management:
      bridge:
        - name: br1
          ip: 192.168.2.1
          mtu: 1450
