---
- name: Create admin-openrc
  copy:
    dest: /root/admin-openrc
    content: |
      OS_PROJECT_DOMAIN_NAME=Default
      OS_USER_DOMAIN_NAME=Default
      OS_PROJECT_NAME={{ group_vars.openstack.admin_project_name }}
      OS_USERNAME={{ group_vars.openstack.admin_user_name }}
      OS_PASSWORD={{ group_vars.openstack.password }}
      OS_AUTH_URL=http://{{ inventory_hostname }}:5000/v3
      OS_IDENTITY_API_VERSION=3
      OS_IMAGE_API_VERSION=2

