---
- name: Create admin-openrc
  copy:
    dest: /root/admin-openrc
    content: |
      export OS_PROJECT_DOMAIN_NAME=Default
      export OS_USER_DOMAIN_NAME=Default
      export OS_PROJECT_NAME={{ group_vars.openstack.admin_project_name }}
      export OS_USERNAME={{ group_vars.openstack.admin_user_name }}
      export OS_PASSWORD={{ group_vars.openstack.admin_password }}
      export OS_AUTH_URL=http://{{ inventory_hostname }}:5000/v3
      export OS_IDENTITY_API_VERSION=3
      export OS_IMAGE_API_VERSION=2

