---
- name: Check the user is already existed or not
  ansible.builtin.script: ./check_duplicate_user.sh "{{ domain_of_user }}" "{{ inner_item.name }}"
  register: result_of_checking
  failed_when: ( result_of_checking.rc not in [0, 1] )

- name: Create a user
  ansible.builtin.command:
    argv: ["openstack", "user", "create", "--domain", "{{ domain_of_user }}", "--password", "{{ inner_item.password }}", "{{ inner_item.name }}"]
  register: result
  when: result_of_checking.rc == 0

- name: Print the result of creating a user
  ansible.builtin.debug:
    msg: "{{ result.stdout.split('\n') }}"
  when: result_of_checking.rc == 0

