---
- name: Include init_keystone_db/main.yml
  include: init_keystone_db/main.yml

- name: Include prepare_keystone_env/main.yml
  include: prepare_keystone_env/main.yml

# Instruction below assumes environment variables are already declared in order to authenticate the endpoint are already declared at controllers.yml.
- name: Include create_domain.yml
  include: create_domain/main.yml

- name: Include create_project.yml
  include: create_project/main.yml

- name: Include create_user.yml
  include: create_user/main.yml

- name: Include create_role.yml
  include: create_role/main.yml

- name: Include create_admin_openrc.yml
  include: create_admin_openrc/main.yml

- name: Include check_after_keystone_has_installed.yml
  include: check_keystone_env/main.yml

