---
- name: Include init_keystone_db/main.yml
  include: init_keystone_db/main.yml

- name: Install packages of keystone
  apt:
    name:
      - keystone

- name: Configure keystone.conf
  ansible.builtin.template:
    src: keystone/keystone.conf.j2
    dest: /etc/keystone/keystone.conf
    owner: keystone
    group: keystone
    mode: '0640'

- name: Sync keystone DB
  ansible.builtin.command:
    argv:
      - su
      - -s
      - /bin/sh
      - -c
      - "keystone-manage db_sync"
      - "{{ group_vars.keystone.user }}"

# Command `keystone-manage fernet_setup` is idempotent
- name: Initialize Fernet key repositories with keystone-manage fernet_setup
  ansible.builtin.command:
    argv:
      - keystone-manage
      - fernet_setup
      - --keystone-user
      - "{{ group_vars.keystone.user }}"
      - --keystone-group
      - "{{ group_vars.keystone.group }}"

# Command `keystone-manage credential_setup` is idempotent
- name: Initialize Fernet key repositories with keystone-manage credential_setup
  ansible.builtin.command:
    argv:
      - keystone-manage
      - credential_setup
      - --keystone-user
      - "{{ group_vars.keystone.user }}"
      - --keystone-group
      - "{{ group_vars.keystone.group }}"

# Command `keystone-manage bootstrap` is idempotent
- name: Bootstrap the Identity service
  ansible.builtin.command:
    argv:
      - keystone-manage
      - bootstrap
      - --bootstrap-password
      - '{{ group_vars.keystone.password }}'
      - --bootstrap-admin-url
      - http://{{ inventory_hostname }}:5000/v3/
      - --bootstrap-internal-url
      - http://{{ inventory_hostname }}:5000/v3/
      - --bootstrap-public-url
      - http://{{ inventory_hostname }}:5000/v3/
      - --bootstrap-region-id
      - "{{ group_vars.openstack.region.name }}"

- name: Set ServerName in apache2 config
  ansible.builtin.template:
    src: templates/apache2/sites-available/000-default.conf.j2
    dest: /etc/apache2/sites-available/000-default.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart apache2

- name: Run notified handler of apache2
  meta: flush_handlers

# This instruction assumes environment variables are already declared in order to authenticate the endpoint are already declared at controllers.yml.
- name: Include create_domain.yml
  include: create_domain/main.yml

- name: Include create_project.yml
  include: create_project/main.yml

- name: Include create_user.yml
  include: create_user/main.yml

- name: Include create_role.yml
  include: create_role/main.yml

- name: Include create_admin_openrc.yml
  include: create_admin_openrc/main.yml

- name: Include check_after_keystone_has_installed.yml
  include: check_keystone_env/main.yml

