---
- name: Declare openstack_service_name for keystone
  set_fact:
    openstack_service_name: "keystone"

- name: Include role-functions to create DB for keystone
  include_role:
    name: functions
    tasks_from: create_db/main.yml
