---
- name: "Stat \"/etc/ceph/ceph.mon.keyring\" whether the file has already existed"
  stat:
    path: "/etc/ceph/ceph.mon.keyring"
    get_checksum: false
    get_md5: false
  register: flag_file

- name: "Generating a key for monitoring a Ceph cluster on \"{{ group_vars.ceph.monitor.hosts.master }}\""
  ansible.builtin.command: ceph-authtool --create-keyring /etc/ceph/ceph.mon.keyring --gen-key -n mon. --cap mon 'allow *'
  when: flag_file.stat.exists == False


- name: "Stat \"/etc/ceph/ceph.client.admin.keyring\" whether the file has already existed"
  stat:
    path: "/etc/ceph/ceph.client.admin.keyring"
    get_checksum: false
    get_md5: false
  register: flag_file

- name: "Generating a key for managing a Ceph cluster on \"{{ group_vars.ceph.monitor.hosts.master }}\""
  ansible.builtin.command: ceph-authtool --create-keyring /etc/ceph/ceph.client.admin.keyring --gen-key -n client.admin --cap mon 'allow *' --cap osd 'allow *' --cap mds 'allow *' --cap mgr 'allow *'
  when: flag_file.stat.exists == False


- name: "Stat \"/var/lib/ceph/bootstrap-osd/ceph.keyring\" whether the file has already existed"
  stat:
    path: "/var/lib/ceph/bootstrap-osd/ceph.keyring"
    get_checksum: false
    get_md5: false
  register: flag_file

- name: "Generating a key for bootstraping a Ceph cluster on \"{{ group_vars.ceph.monitor.hosts.master }}\""
  ansible.builtin.command: ceph-authtool --create-keyring /var/lib/ceph/bootstrap-osd/ceph.keyring --gen-key -n client.bootstrap-osd --cap mon 'profile bootstrap-osd' --cap mgr 'allow r'
  when: flag_file.stat.exists == False


- name: "Check a flag that means \"ceph-authtool /etc/ceph/ceph.mon.keyring --import-keyring /etc/ceph/ceph.client.admin.keyring\" was finished"
  stat:
    path: /root/.ceph_authtool_ceph_client_admin_keyring_has_finished
  register: flag_file

- name: "Import a keyring \"client.admin\" from \"/etc/ceph/ceph.client.admin.keyring\" to \"/etc/ceph/ceph.mon.keyring\""
  ansible.builtin.command: ceph-authtool /etc/ceph/ceph.mon.keyring --import-keyring /etc/ceph/ceph.client.admin.keyring
  when: flag_file.stat.exists == False

- name: "Create a flag that means \"ceph-authtool /etc/ceph/ceph.mon.keyring --import-keyring /etc/ceph/ceph.client.admin.keyring\" was finished"
  copy:
    content: ""
    dest: /root/.ceph_authtool_ceph_client_admin_keyring_has_finished
    force: no
    owner: root
    group: root
    mode: '0640'


- name: "Check a flag that means \"ceph-authtool /etc/ceph/ceph.mon.keyring --import-keyring /var/lib/ceph/bootstrap-osd/ceph.keyring\" was finished"
  stat:
    path: /root/.ceph_authtool_bootstrap_osd_ceph_keyring_has_finished
  register: flag_file

- name: "Import a key \"client.bootstrap-osd\" from \"/var/lib/ceph/bootstrap-osd/ceph.keyring\" to \"/etc/ceph/ceph.mon.keyring\"."
  ansible.builtin.command: ceph-authtool /etc/ceph/ceph.mon.keyring --import-keyring /var/lib/ceph/bootstrap-osd/ceph.keyring
  when: flag_file.stat.exists == False

- name: "Create a flag that means \"ceph-authtool /etc/ceph/ceph.mon.keyring --import-keyring /var/lib/ceph/bootstrap-osd/ceph.keyring\" was finished"
  copy:
    content: ""
    dest: /root/.ceph_authtool_bootstrap_osd_ceph_keyring_has_finished
    force: no
    owner: root
    group: root
    mode: '0640'


- name: "Find keyrings \"/etc/ceph/ceph.*.keyging\" on a monitor node \"{{ group_vars.ceph.monitor.hosts.master }}\" for Ceph"
  find:
    paths: /etc/ceph
    file_type: file
    patterns: "ceph.*.keyring"
  register: filelist

- name: "Change permisions of keyrings \"/etc/ceph/ceph.*.keyring\" on a host \"{{ group_vars.ceph.monitor.hosts.master }}\" for Ceph"
  ansible.builtin.file:
    dest: "{{ item.path }}"
    owner: ceph
    group: ceph
  with_items: "{{ filelist.files }}"


- name: "Change permissions of directories recursively on a host {{ group_vars.ceph.monitor.hosts.master }} for Ceph"
  ansible.builtin.file: 
    path: "{{ item }}"
    state: directory
    recurse: yes
    owner: ceph
    group: ceph
  with_items:
    - "/var/lib/ceph/mon/ceph-{{ inventory_hostname }}"
    - "/var/lib/ceph/bootstrap-osd"

# TODO: This instruction should be registered as a handler
- name: "Enable \"ceph-mon@{{ group_vars.ceph.monitor.hosts.master }}\" on a host \"{{ group_vars.ceph.monitor.hosts.master }}\""
  ansible.builtin.systemd:
    name: "ceph-mon@{{ group_vars.ceph.monitor.hosts.master }}"
    state: restarted
    enabled: true

