---
# Target hosts to create ceph volumes are belonging groups 'cinders' or 'storages'.
- name: Declare a variable group_for_ceph to detect to create ceph volumes for 'cinder' nodes
  set_fact:
    group_for_ceph: "cinders"
  when: '"cinders" in group_names'

- name: Declare a variable group_for_ceph to detect to create ceph volumes for 'storage' nodes
  set_fact:
    group_for_ceph: "storages"
  when: '"storages" in group_names'

- name: "Find an element of hosts"
  set_fact:
    element_of_node: "{{ group_vars.hosts[group_for_ceph] | selectattr(\"name\", \"equalto\", inventory_hostname) | first }}"

- name: "Failed if the variable \"element_of_node\" has not be declared."
  ansible.builtin.fail:
    msg: "The variable \"element_of_node\" has not declared. Is this host({{ inventory_hostname }}) has belonging in \"group_vars.hosts.cinder\" or \"group_vars.hosts.\"? Content of them will be dumped.{{ '\n' }}group_vars.hosts.cinder => {{ group_vars.hosts.cinder }}{{ '\n' }}group_vars.hosts.storage => {{ group_vars.hosts.storage }}"
  when: element_of_node is not defined

# Create ceph volumes if current host is belonging in group 'cinders' or 'storages'.
# And each group_vars.hosts.${group_name}[] have elements 'storage' and 'storage.cinder'.
# ex) group_vars.hosts.cinders[0].
- name: "Create ceph volume for {{ inventory_hostname }}"
  include_tasks: do_create_ceph_volume.yml
