---
# This instruction assumes some variables should already be declared.
# group:
#   An object of the group that will be added
# group.name:
#   Name of the security group that will be created.
# group.description
#   Description of the security group
# group.rules[]
#   Rules of the security group that will be created in this security group.

- name: Check whether the security group is already existed
  ansible.builtin.script: ./check_duplicate_security_group.sh "{{ group.name }}"
  register: result_of_checking_security_group
  failed_when: ( result_of_checking_subnet.rc not in [0, 1] )

- name: Block of creating a security group
  block:
    - name: Print a security group that will be created.
      ansible.builtin.debug:
        msg: "group.name==\"{{ group.name }}\", group.description=\"{{ group.description }}\""

    - name: Create a security group if it was not already existed
      ansible.builtin.command:
        argv: ["openstack", "security", "group", "create", "{{ group.name }}", "--description", "{{ group.description }}"]
  when: result_of_checking_subnet.rc == 0

- name: Include do_create_rule.yml
  include: do_create_rule.yml
  loop_control:
    loop_var: rule
  loop: "{{ group.rules }}"

