---
#- name: "Setting permission of the directory /etc/swift"
#  ansible.builtin.file:
#    path: "/etc/swift"
#    owner: root
#    group: swift
#    state: directory
#    recurse: yes

- name: "Setting permission of the directory /etc/swift"
  command: chown -R root:swift /etc/swift
