---
# Variables that will be passed.
#   client_credential.name:
#     A name of credential.
#   client_credential.permission_of_mon:
#     A permission of monitor
#   client_credential.permission_of_osd:
#     A permission of OSD

- name: "Creating client credential (client_credential.name=\"{{ client_credential.name }}\", client_credential.permission_of_mon={{ client_credential.permission_of_mon }}, client_credential.permission_of_osd={{ client_credential.permission_of_osd }})"
  ansible.builtin.script: create_client_credential.sh "{{ client_credential.name }}" "{{ client_credential.permission_of_mon }}" "{{ client_credential.permission_of_osd }}"

