---
- name: Install packages of glance
  apt:
    name:
      - glance

- name: Set /etc/glance/glance-api.conf
  ansible.builtin.template:
    src: glance/glance-api.conf.j2
    dest: /etc/glance/glance-api.conf
    owner: root
    group: glance
    mode: 0640
    backup: yes
  notify: Restart glance-api

- name: Check a flag that means set config and sync db was finished
  stat:
    path: /root/.ansible_glance_sync_db_was_finished
  register: flag_file

- name: Sync database for glance
  ansible.builtin.command:
    argv: ["su", "-s", "/bin/sh", "-c", "glance-manage db_sync", "glance"]
  when: not flag_file.stat.exists

- name: Create a flag that means sync db was finished
  copy:
    content: ""
    dest: /root/.ansible_glance_sync_db_was_finished
    force: no
    owner: root
    group: root
    mode: '0640'

- name: Enable service glance-api
  ansible.builtin.service:
    name: glance-api
    enabled: yes

- name: Run notified handler of glance-api
  meta: flush_handlers

