---
- name: Install packages for rabbitmq-server
  apt:
    name:
      - memcached
      - python3-memcache
  register: apt_result
  retries: 360
  delay: 5
  until: apt_result is success

- name: Modify /etc/memcached.conf
  ansible.builtin.template:
    src: memcached.conf.j2
    dest: /etc/memcached.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart memcached

- name: Run notified handler of memcached
  meta: flush_handlers

