---
- name: Install packages of Horizon for controllers
  apt:
    name:
      # Install python3-django-environ to enabling Django compressor
      - openstack-dashboard
      - python3-django-environ
  register: apt_result
  retries: 360
  delay: 5
  until: apt_result is success

- name: Update alternatives for python3
  community.general.alternatives:
    name: python
    path: /usr/bin/python3
    link: /usr/bin/python
    state: present
    priority: 10

- name: Set /etc/openstack-dashboard/local_settings.py for Horizon
  ansible.builtin.template:
    src: openstack-dashboard/local_settings.py.j2
    dest: /etc/openstack-dashboard/local_settings.py
    owner: root
    group: horizon
    mode: '0640'
    backup: yes
  notify: ["Restart apache2"]

- name: Set /etc/apache2/conf-available/openstack-dashboard.conf for Horizon
  ansible.builtin.template:
    src: apache2/conf-available/openstack-dashboard.conf.j2
    dest: /etc/apache2/conf-available/openstack-dashboard.conf
    owner: root
    group: root
    mode: '0644'
    backup: yes
  notify: ["Restart apache2"]

- name: Run a script do_django_compress.sh if compressing is needed
  ansible.builtin.script: do_django_compress.sh

- name: Run notified handlers of Horizon
  meta: flush_handlers

