---
# Instructions for Nova controller nodes
- name: A block to build Nova for controller nodes
  block:
    - name: Include create_dbs/main.yml
      include_tasks: create_dbs/main.yml

    - name: Include create_services/main.yml
      include_tasks: create_services/main.yml

    - name: Include create_endpoints/main.yml
      include_tasks: create_endpoints/main.yml

    - name: Include install_packages/controllers/main.yml for controllers
      include_tasks: install_packages/controllers/main.yml

    - name: Include set_configuration/controllers/main.yml for controllers
      include_tasks: set_configuration/controllers/main.yml
  when: "'controllers' in group_names"

# Instructions for Nova compute nodes
- name: A block to build Nova for computes nodes
  block:
    - name: Include install_packages/computes/main.yml for computes
      include_tasks: install_packages/computes/main.yml

    - name: Include set_configuration/computes/main.yml for computes
      include_tasks: set_configuration/computes/main.yml
  when: "'computes' in group_names"
