---
- name: A block for OpenStack Compute service
  block:
    - name: Include create_dbs/main.yml
      include: create_dbs/main.yml

    - name: Include create_services/main.yml
      include: create_services/main.yml

    - name: Include create_endpoints/main.yml
      include: create_endpoints/main.yml

    - name: Include prepare_openstack_services/main.yml
      include: prepare_openstack_services/main.yml

# TODO: Create instructions to build WSGI environment from package manager

