---
- name: Enable authentication with unix socket
  ansible.builtin.command:
    argv:
      - mysql
      - -e
      - "UPDATE mysql.global_priv SET priv=json_set(priv, '$.password_last_changed', UNIX_TIMESTAMP(), '$.plugin', 'mysql_native_password', '$.authentication_string', 'invalid', '$.auth_or', json_array(json_object(), json_object('plugin', 'unix_socket'))) WHERE User='root';"

- name: Flush privileges after enabling authentication with unix socket
  ansible.builtin.command:
    argv:
      - mysql
      - -e
      - "FLUSH PRIVILEGES;"

- name: Set the root password
  ansible.builtin.command:
    argv:
      - mysql
      - -e
      - "UPDATE mysql.global_priv SET priv=json_set(priv, '$.plugin', 'mysql_native_password', '$.authentication_string', PASSWORD('{{ group_vars.sql.password }}')) WHERE User='root';"

- name: Flush privileges after setting the root password
  ansible.builtin.command:
    argv:
      - mysql
      - -e
      - "FLUSH PRIVILEGES;"

