---
- name: Install packages of Nova
  apt:
    name:
      - nova-api
      - nova-conductor
      - nova-novncproxy
      - nova-scheduler

- name: Set /etc/nova/nova.conf
  ansible.builtin.template:
    src: nova/nova.conf.j2
    dest: /etc/nova/nova.conf
    owner: root
    group: nova
    mode: 0640
    backup: yes
  register: template_result

# There are no patterns to detect options to sync DB.
# So they are written as hard coded so far.
- name: Sync database for Nova
  ansible.builtin.command:
    argv: ["su", "-s", "/bin/sh", "-c", "{{ item }}", "{{ group_vars.nova.user }}"]
  loop:
    - "nova-manage api_db sync"
    - "nova-manage cell_v2 map_cell0"
    - "nova-manage cell_v2 create_cell --name=cell1 --verbose"
    - "nova-manage db sync"
  when: template_result.changed

- name: Check the result of syncing Nova DB
  ansible.builtin.command:
    argv: ["su", "-s", "/bin/sh", "-c", "nova-manage cell_v2 list_cells", "nova"]
  register: result

- name: Print the result of syncing Nova DB
  ansible.builtin.debug:
    msg: "{{ result.stdout.split('\n') }}"

- name: Restart services related Nova
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - nova-api
    - nova-scheduler
    - nova-conductor
    - nova-novncproxy
  when: template_result.changed

