---
- name: "Push the file to {{ inventory_hostname }} for compute nodes of Ceph"
  copy:
    src: ".buffer/{{ item | basename }}"
    dest: "{{ item }}"
  with_items:
    # "/etc/ceph/ceph.client.cinder.keyring" will also be used as a secret of libvirtd.
    - "/etc/ceph/ceph.client.cinder.keyring"

- name: "Find ceph configurations in the directory \"/etc/ceph/ceph*\" on a monitor node \"{{ inventory_hostname }}\" for Ceph"
  find:
    paths: /etc/ceph
    file_type: file
    patterns: "ceph.*"
  register: filelist

- name: "Change permisions of files \"/etc/ceph/ceph.*\" on a monitor node \"{{ inventory_hostname }}\" for Ceph"
  ansible.builtin.file:
    dest: "{{ item.path }}"
    owner: ceph
    group: ceph
  with_items: "{{ filelist.files }}"

